### ISSUE TITLE
bug: Timeline Links do not show up in the desk/portal

### ISSUE THREAD

**Issue by ahmadpak** [frappe/helpdesk#1000]
When replying to a ticket using the timeline links do not show up in the HelpDesk desk/portal

**Timeline Links**
<img width="1233" alt="image" src="https://user-images.githubusercontent.com/7881486/219819724-0928573b-df91-4313-9e33-656892747a5a.png">

**Linked Communication showing up in the Frappe Desk**
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/7881486/219820030-f8bb4dc1-1cf4-4a73-a2d5-bbb46bddc16a.png">

**Linked Communication not showing up in the HelpDesk Desk/Portal**
<img width="693" alt="image" src="https://user-images.githubusercontent.com/7881486/219819845-fdafbe7e-c780-4a08-978e-223fe95df67f.png">

**Comment by RitvikSardana** [comment]
Part of old helpdesk, hence closing
