### ISSUE TITLE
feat: Show Connections in the Ticket

### ISSUE THREAD

**Issue by ahmadpak** [frappe/helpdesk#1001]
It would be very nice to be able to show connections in the ticket 

<img width="533" alt="image" src="https://user-images.githubusercontent.com/7881486/219820200-b03ebe60-75c2-4107-a2a6-aef4adc66399.png">

**Comment by harshit-30** [comment]
Surely, once we integrate with ERPNext - we will add this to our list.

**Comment by RitvikSardana** [comment]
Part of old helpdesk, hence closing
