### ISSUE TITLE
Bug Overview and missing Functionality 

### ISSUE THREAD

**Issue by prononext** [frappe/helpdesk#1063]
First of all, I think that nicely designed Support Module is a very promising function, urgently needed for ERPNext, thank you very much for your effort. 

I have evaluated Frappedesk for usage in a production environment but the result was the following.

**I installed it to following System following the the README in this repository**

ERPNext: v14.18.3 (version-14)
Frappe Framework: v14.28.2 (version-14)
FrappeDesk: v0.6.5 (main)
Frappe HR: v14.1.2 (version-14)

After a couple of fails and back and forth with node versions it finally got installed.

# Functionality Overview

## General
- [ ] Strange reloads after every action taken
- [ ] No direct search, only filter with multilevel input required, makes the handling quite slow

## Ticket's:
- [ ] Creating by External Party - does not work even if incoming email is configured correctly 
- [ ] Creating by Agent not working, as no possibility to add "created by" nor Customer" (only when on Classic ERPNext GUI.
- [ ] Creating from FD Customer or Contact is also not working. On Customer the Contact cannot be added and on Contact the Create Ticket button does not work
- [ ] E-Mail raised by is only visible when clicking on reply
- [ ] E-Mail raised by cannot be changed, not even in ERPNext GUI (Ticket Handover to client stakeholders)
- [ ] Reply is not working - even if email is configured correctly with a default account "Internal Server Error" all other emails on ERPNext working

## Knowledge Base
- [ ] Categories can be added
- [ ] Articles cannot be added as the created categories are not visible in the article and without mandatory category no article can be created

## Customers + Contacts
- [x] Customers and Contacts can be created but cannot really be used because of the above stuff....
- [ ] Customers are not taken from ERPNext, which absolutely makes no sense, no one wants double entries and for billing and reporting on volume that is a no-go
- [x] Contacts are taken from ERPNext but without Company affiliation
- [ ] Filter are not working on Contacts

## Settings
- [ ] Function to change the url /frappedesk
- [ ] Function to change the Favicon for Backend and Frontend
- [ ] Function to change the Splash Logo
- [ ] Function to change the Logo on Customer Login
- [ ] Function to change Menu Logo for Backend
- [ ] Function to disable Customer Login / public login site for Frappedesk
- [ ] Function to assign different E-Mail accounts to teams

This is just a rough overview of the bugs I found and functions I missed. 
As I noticed that the product is definately far from production readiness, but I hope it will be soon and working seamlessly with ERPNext. Thank you very much.

**Comment by ssiyad** [comment]
We wanted to thank you for taking the time to review helpdesk. Your insights and feedback were incredibly valuable, and we appreciate the effort you put into evaluating our work.

Your comments have provided us with valuable information that will help us improve helpdesk and make it more user-friendly. Your review has also helped us identify areas that need more attention and allowed us to address any issues that were previously unnoticed.

Thank you so much for your time and valuable feedback. It means a lot!
