### ISSUE TITLE
Option Reply to all option

### ISSUE THREAD

**Issue by JoSoG89** [frappe/helpdesk#1088]
By default when an agent reply to an email the option of reply to all is necessary, now we can see the recipients of the original mail, but when the agent try to reply we have 2 issues:
1.- by default the reply is only for who send the mail, the CC people dont appear.
2.- If the agent put the other people in CC the mail is sended independed for each one and nobody know other people is in CC.

**Comment by ssiyad** [comment]
Can you try latest version? These issues should be fixed already

**Comment by JoSoG89** [comment]
> Can you try latest version? These issues should be fixed already

I update few minutes ago

![imagen](https://user-images.githubusercontent.com/106213922/229908280-c2e81255-3d26-48ff-89bf-0bdf2ff9aa35.png)

**Comment by RitvikSardana** [comment]
Exists in Frappe Helpdesk,
https://frappecloud.com/helpdesk/signup
