### ISSUE TITLE
Cant  update HelpDesk

### ISSUE THREAD

**Issue by JoSoG89** [frappe/helpdesk#1090]
Im stuck in version 0.6.0 and when i try to update i get this message:
![image](https://user-images.githubusercontent.com/106213922/229967018-0ef969ac-0cc0-4d77-807f-c1a800e3351a.png)

warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
 

Any Help?

**Comment by ssiyad** [comment]
Use `bench update`

**Comment by ssiyad** [comment]
Where you able to achieve this?
