### ISSUE TITLE
Visit Helpdesk Takes to my-tickets Web Page

### ISSUE THREAD

**Issue by HnSSiva** [frappe/helpdesk#1120]
Configured a User with Agent Role.

When that User tried the Visit Helpdesk it takes to the Web Page View, /helpdesk/my-tickets.

It should take us to the Ticket Page view. Are we missing some configuration?

ERPNext: v14.21.0 (version-14)
Frappe Framework: v14.32.1 (version-14)
Helpdesk: v0.8.1 (main)

**Comment by ssiyad** [comment]
This is a known bug. Will be fixed in coming week

**Comment by HnSSiva** [comment]
Sure, thanks. Waiting for the same to start using the App.

**Comment by HnSSiva** [comment]
Hi, thanks for the 0.8.2 Update. In this we don't see the fix for #1114 included.

Just to note that in __init__.py we see the reference as 0.8.1

Thanks

**Comment by ssiyad** [comment]
That PR is not included in a release yet. You can always choose to use `main`.

Sorry about the version issue, it is not always synced due to human errors. We will soon have an system for automated releases. If you find any such niggles, don't hesitate to raise a PR. It will be a great help!
