### ISSUE TITLE
There is nothing 404 error on helpdesk

### ISSUE THREAD

**Issue by bhickta** [frappe/helpdesk#1125]
https://support.xyz.com/helpdesk
https://support.xyz.com/helpdesk/tickets

There's nothing here
The page you are looking for has gone missing.

but it is working when i am not using domain name in my dev environment

All other things are working fine

**Comment by ssiyad** [comment]
Which commit are you on? Is there any error anywhere?

**Comment by bhickta** [comment]
I am on the latest commit
Doctypes and other functionalities are working fine.

I have multi tenancy dns turned on

A record is set to:
1.  @ - ip-address - resolves to --> example.com
2. support - ip-address - resolves to --> support.example.com

Apps - installed
frappe   14.32.1 version-14
helpdesk 0.8.1   main
erpnext  14.21.0 version-14

**Comment by bhickta** [comment]
Helpdesk is working fine on:

no dns multitenancy, production env, no domain setup, ubuntu lts 22.04

frappe           14.31.0 version-14
payments         0.0.1   develop
erpnext          14.20.1 version-14
hrms             1.0.0   develop
india_compliance 14.1.0  version-14
helpdesk         0.8.1   main

**Comment by ssiyad** [comment]
This is probably an issue with your DNS/multi-tenancy setup

**Comment by ssiyad** [comment]
@bhickta did you have any luck fixing this? If not, you could start by asking in the [forum](https://discuss.frappe.io/) or [telegram channel](https://t.me/frappeframework)
