### ISSUE TITLE
Issues In Ticket Details Tab

### ISSUE THREAD

**Issue by Shivam327** [frappe/helpdesk#1180]
1) Cannot Change Assignee
![image](https://github.com/frappe/helpdesk/assets/23412311/6bf31842-1da1-439c-8af9-15f48a635444)
2) Ticket History Tab is not showing any history, (I changed ticket Type and Status but it was not reflected in the history)
![image](https://github.com/frappe/helpdesk/assets/23412311/fd2a8ffb-c9b0-4b0a-8b57-56a2b16fb3b2)

PS: I may not know the perfect feature of Ticket History But if any user makes the changes to the ticket it should be added in the ticket history so we can monitor it.

**Comment by ssiyad** [comment]
There is a newer version available. Update and check if the issue is fixed

**Comment by Shivam327** [comment]
Yes,This issue has been solved
