### ISSUE TITLE
Cannot reply to ticket

### ISSUE THREAD

**Issue by michellealva** [frappe/helpdesk#1213]
<img width="1665" alt="image" src="https://github.com/frappe/helpdesk/assets/50285544/b6b0fa2e-403a-4da3-b4fa-0409fb03f9ba">

P.s. comments work though

**Comment by prasathsekar** [comment]
![Screenshot 2023-05-26 at 5 48 18 PM](https://github.com/frappe/helpdesk/assets/25291469/29f21cd2-04c4-4f7d-93e1-ba62b1d4f01e)
Getting Same Error, unable to reply by tagging the email.

Comment and Reply is working.

**Comment by ssiyad** [comment]
This is old version of Helpdesk. Update to latest and try

**Comment by prasathsekar** [comment]
How can i find the current version and how can i update it to the new version 

Any material guidance is there?

**Comment by ssiyad** [comment]
@prasathsekar Which commit? Even though there are versioned releases, you can always jump ahead to newest commits. Also, the screenshot you see in the beginning is old design. Hence, is an old version

**Comment by prasathsekar** [comment]
![Screenshot 2023-05-26 at 7 22 33 PM](https://github.com/frappe/helpdesk/assets/25291469/54d1f321-333d-4e03-a4e7-2ae9074e2358)
Screenshot for your referance

**Comment by ssiyad** [comment]
In that case, create a different ticket. This seems unrelated to original issue
