### ISSUE TITLE
Question: Multiple Email Assignment to Agents

### ISSUE THREAD

**Issue by prasathsekar** [frappe/helpdesk#1232]
We have two Emails, one is support@xyz.com and desk@xyz.com.

Whenever the Email receives, i am linking it to the HD Ticket. But the ticket are assigned only to Agent 1 & Agent 2.

Can we Forward the Support@xyz.com to Agent 1 & Agent 2 in Round Robin and desk@xyz.com to Agent 3 & Agent 4 in round robin ?

Can you help us with any example ?

**Comment by ssiyad** [comment]
This is currently not supported in Helpdesk. We might consider this in future though
