### ISSUE TITLE
Unable to reply to Email

### ISSUE THREAD

**Issue by prasathsekar** [frappe/helpdesk#1236]
Currently using below version of frappe and helpdesk

frappe 14.36.2
helpdesk 0.8.4

Whenever the ticket is created i can able to click on the below text and send the reply or comment.

But when i click on the three-dot and try to reply, it shows an below error.

![Screenshot 2023-05-26 at 5 48 18 PM](https://github.com/frappe/helpdesk/assets/25291469/7f8e0f33-19e2-4cd3-b07a-17a6ab01dc45)
![Screenshot 2023-05-26 at 7 22 33 PM](https://github.com/frappe/helpdesk/assets/25291469/9e4eada7-f53f-4264-85fb-1b50443f7c71)

**Comment by ssiyad** [comment]
I cannot reproduce this. Can you specify Frappe Framework version, Helpdesk version/commit and any other relevant information?

**Comment by PatelN123** [comment]
@ssiyad I can reproduce this. 

![image](https://github.com/frappe/helpdesk/assets/79650289/c1834a5c-de7e-47c8-a53d-bb3d55b75620)

**Comment by ssiyad** [comment]
@PatelN123  `tabArticle` should have been replaced by `tabHD Article`. Can you show where this error originates? Can you post the full error log?
