### ISSUE TITLE
New tickets are not getting created

### ISSUE THREAD

**Issue by nshah14285** [frappe/helpdesk#1248]
Hello,

We have setup helpdesk production on our staging server as we are planning to use it for our production site.
First two days new tickets were getting created properly, but suddenly after that new tickets were stopped getting created.

**Version installed on server** 
Ubuntu 22.04.2 LTS
Python 3.10.6
Redis 6:7.0.11-1rl1~jammy1
MariaDB 1:10.6.12
frappe: 15.x.x-develop (branch: develop)
helpdesk:  0.8.4 (branch: main)

We were able to send/receive emails from existing tickets, these tickets were created before the issue started.

We also notice below lines in nginx logs, it continuously getting logged in the nginx access log.

```
xx.xx.xx.xx - - [05/Jun/2023:10:28:32 +0000] "GET /helpdesk HTTP/1.1" 200 389 "https://example.com/app/helpdesk" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0"
127.0.0.1 - - [05/Jun/2023:10:28:32 +0000] "GET /socket.io/?EIO=4&transport=polling&t=OYB6Uuj HTTP/1.1" 301 178 "https://example.com/helpdesk" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0"

```

We also notice below error in worker.error.log, do not know whether it is related or not.

```
ERROR   PropertyValue: Missing token for production Choice(ColorValue, Dimension, URIValue, Value, variable, MSValue, CSSCalc, function): ('HASH', '#0000001a', 1, 3198)
ERROR   PropertyValue: Unknown syntax or no value: 0 3px 6px #0000001a
ERROR   CSSStyleDeclaration: Syntax Error in Property: box-shadow:0 3px 6px #0000001a

```

Please find attached error log

[error.txt](https://github.com/frappe/helpdesk/files/11651498/error.txt)

Let me know if you need any more details.

**Comment by nshah14285** [comment]
@ssiyad 

Thank You for the quick fix.
I have updated to the latest version and the new ticket has been created.

I have also noticed that auto refresh is not working.
Could you please check.

Thank You.

**Comment by ssiyad** [comment]
> auto refresh is not working

Can you create another issue with bit more context?
