### ISSUE TITLE
Customer Portal Ticket

### ISSUE THREAD

**Issue by jecinthamary** [frappe/helpdesk#1254]
ERPNext: v14.26.0 (version-14)
Frappe Framework: v14.37.0 (version-14)
Helpdesk: v0.9.1 (main)

User already created tickets not able to see in list view

![image](https://github.com/frappe/helpdesk/assets/126246621/119cc1ef-d202-4b49-89ad-4694f9f6bc17)

**Comment by niraj2477** [comment]
Fixed in the PR [here](https://github.com/frappe/helpdesk/pull/1270)
