### ISSUE TITLE
Closed ticket section not visible

### ISSUE THREAD

**Issue by nestorbird** [frappe/helpdesk#1262]
Hello,

When i'm moving my site from server to Frappe Cloud and restoring my data at that time my closed tickets are not visible.

<img width="896" alt="image" src="https://github.com/frappe/helpdesk/assets/121154920/8805c1c9-d539-4ed3-837e-0bf804241450">

On my server this closed ticket section is showing the tickets.

**Comment by ssiyad** [comment]
Are you sure there are some closed tickets assigned to 'Administrator'? Can you verify this from desk (backend)?
