### ISSUE TITLE
Error while creating new ticket in helpdesk.

### ISSUE THREAD

**Issue by asoral** [frappe/helpdesk#1266]
while creating new ticket showing error, refer screenshot below
![image](https://github.com/frappe/helpdesk/assets/11851156/3c59bced-2707-4384-ad55-3ed50e6e565f)

**Comment by ssiyad** [comment]
Can you click on any of the 404 errors (it takes you to the request) and send what is in the response?

**Comment by asoral** [comment]
> Can you click on any of the 404 errors (it takes you to the request) and send what is in the response?

![image](https://github.com/frappe/helpdesk/assets/11851156/839ca7f6-74af-456f-8b44-43a79c8ad8f5)

**Comment by asoral** [comment]
> Can you click on any of the 404 errors (it takes you to the request) and send what is in the response?

I checked it and found that it doesn't work when there is no "Default" HD Ticket Template in the database. I had deleted the Default and created my own list of templates so that we can use the ones we need and remove the ones we don't. I could have otherwise also disabled it but the feature to disable does not exist, so I had to delete it.

Furthermore, the old feature where user selected the template first and then created the ticket based on the fields mentioned in the HD Ticket Template is also gone. That was really useful and the most logical thing to have because not all ticket sare of same type (default) and we need different fields for every type of ticket to ensure we have evrything needed to troublshoot.

**Comment by ssiyad** [comment]
> Furthermore, the old feature where user selected the template first and then created the ticket based on the fields mentioned in the HD Ticket Template is also gone

This will come back later once existing features are stabilised. Until then, you will have to adjust with `Default`
