### ISSUE TITLE
Portal not displaying tickets

### ISSUE THREAD

**Issue by monolithonadmin** [frappe/helpdesk#1281]
![Screenshot 2023-06-22 11 07 36 AM](https://github.com/frappe/helpdesk/assets/5338127/f2fe92df-81e7-4d27-952b-622a553768fc)
I have tested the latest nightly version on frappecloud, as well as the official frappedesk paid solution, and I encountered an issue where the portal and frappecloud's ticket system both fail to list tickets created under certain circumstances.

Please fix the nightly version, bc we have issue with the older too. 

I tested release 0.9.1 on frappecloud, and it works fine under normal circumstances.
However, if a ticket is created via email and later I create a portal user for the reporter of that ticket, a problem arises.
Even if the "Raised By (Email)" field's content remains the same, the client cannot see their ticket. 

They can see the ticket in the list view, but they are unable to open it and view the details.
If I manually share all the relevant tickets with the specific user, they are then able to see them.

Expected Behavior:
When a portal user is added after a ticket is created via email, the user should be able to view and access the ticket. 

Steps to Reproduce:

Install frappecloud or use the official frappedesk paid solution.
Create a ticket via email.
Create a portal user for the reporter of the ticket.
Observe that the ticket is not listed in both the portal or cannot be opened or viewed by the client.

Additional Information:

This issue occurs specifically when a ticket is created from email and a portal user is added later.
The "Raised By (Email)" field contains the correct content.
Manually sharing the ticket with the user allows them to see it.

**Comment by ssiyad** [comment]
> This issue occurs specifically when a ticket is created from email and a portal user is added later.

Looks like an edge case. I will look into this

**Comment by monolithonadmin** [comment]
Thank you for your reply @ssiyad 

You are right its an edge case on 0.9.1

**Comment by RitvikSardana** [comment]
Part of old helpdesk, hence closing
