### ISSUE TITLE
Helpdesk Attachment not working

### ISSUE THREAD

**Issue by asoral** [frappe/helpdesk#1309]
Attachment button is not working from Customer portal.
please refer attachment.
![image](https://github.com/frappe/helpdesk/assets/11851156/f04d303f-9e9d-45db-93e3-8920b053a4d0)

**Comment by ssiyad** [comment]
This has been reported and fixed recently. Maybe try with a newer version?

**Comment by asoral** [comment]
Which version, is it fixed ?

**Comment by ssiyad** [comment]
Try latest commit
