### ISSUE TITLE
List View cannot be disabled in Webform

### ISSUE THREAD

**Issue by willspenc** [frappe/helpdesk#1310]
The Showlist setting cannot be unset in "List Settings" on Ticket Webform.

**Comment by ssiyad** [comment]
Explain please? I didn't get it

**Comment by willspenc** [comment]
website -> webform
Select "HD Ticket"  ( webform for HD Ticket )
Open "HD Ticket" webform
Select "Settings" tab

Scroll down halfway to " List setting" and open.
In there is a check-box for  : "show list" which I assume determines if the entire list of HD Tickets are displayed
in the webform. 
If I try and untick this, it does untick, but on "saving" it is selected again.

**Comment by willspenc** [comment]
website -> webform
Select "HD Ticket" ( webform for HD Ticket )
Open "HD Ticket" webform
Select "Settings" tab

Scroll down halfway to " List setting" and open.
In there is a check-box for : "show list" which I assume determines if the
entire list of HD Tickets are displayed
in the webform.
If I try and untick this, it does untick, but on "saving" it is selected
again.


I sm expecting it to stay "untcked"

**Comment by willspenc** [comment]
Good day

Any news on this ?

**Comment by RitvikSardana** [comment]
should be fixed now, re-open if the issue still persists
