### ISSUE TITLE
Cannot reassign ticket to another agent

### ISSUE THREAD

**Issue by michellealva** [frappe/helpdesk#1325]
Steps:
1. In the portal, go to an already assigned ticket
2. Try changing the name of the agent and click on save
3. On save, the agent name reverts to the original agent's name.

Edit: On refresh it is visible.

**Comment by michellealva** [comment]
@ssiyad This is now resolved, however, there is a slight gitch as you can see in the GIF below:



https://github.com/frappe/helpdesk/assets/50285544/45087b99-83ae-4ef0-8a3f-e629a88d4a4c

**Comment by nextchamp-saqib** [comment]
this is happening because you are updating UI after network request is completed
if the UI is updated immediately, and then the network request is made, it may fix the issue
