### ISSUE TITLE
Custom fields added via HD Ticket Template not reflecting in filters

### ISSUE THREAD

**Issue by michellealva** [frappe/helpdesk#1328]
I've added a couple of new fields via HD Ticket Template, however I'm unable to add them as filters here

<img width="1340" alt="Screenshot 2023-07-24 at 8 22 05 PM" src="https://github.com/frappe/helpdesk/assets/50285544/4293d116-ea86-4cf8-b5b2-cae9ac28dbc1">

<img width="1680" alt="Screenshot 2023-07-24 at 8 21 51 PM" src="https://github.com/frappe/helpdesk/assets/50285544/6910645e-bafb-4ab6-8b52-2c594e2a039a">

**Comment by ssiyad** [comment]
Current implementation of custom fields will be scrapped. Hence there is no plan to filter by custom fields atm
