### ISSUE TITLE
Improve UX of add a new agent page

### ISSUE THREAD

**Issue by michellealva** [frappe/helpdesk#1329]
- [ ] Add space between buttons
- [ ] Make the enter button explicit
- [ ] The box which captures the agents looks editable at the start. Maybe do not show it till at least an agent is added?

<img width="1680" alt="Screenshot 2023-07-24 at 8 47 57 PM" src="https://github.com/frappe/helpdesk/assets/50285544/afa1dfd4-6bb9-4a2e-bd23-3c45884de783">

**Comment by nextchamp-saqib** [comment]
fixed with https://github.com/frappe/helpdesk/pull/1352
