### ISSUE TITLE
Change empty message on helpdesk agent page

### ISSUE THREAD

**Issue by michellealva** [frappe/helpdesk#1333]
![IMAGE 2023-07-24 21:12:30](https://github.com/frappe/helpdesk/assets/50285544/90234e0a-a9cf-4372-b6d9-bb42797205d0)

https://github.com/frappe/helpdesk/blob/main/desk/src/components/HelpdeskTable.vue#L206

**Comment by michellealva** [comment]
https://github.com/frappe/helpdesk/pull/1334

**Comment by michellealva** [comment]
closed via https://github.com/frappe/helpdesk/pull/1334

**Comment by athul** [comment]
Umm @michellealva why though? The empty message which it was changed to is just bland, like "Such Empty" was a fun and casual way of saying "nothing more". Quirky messages are part of development, they convey a lot more. These small changes matter for devs and the end user else we are just building an "enterprisey" stuff which only some niche uses than a general helpdesk software.

My 2 cents!

**Comment by netchampfaris** [comment]
@athul Helpdesk gives off an amateurish feel when "quirky" copy is used in the UI. I would prefer standard and clear messages that don't require an understanding of meme culture 😄

**Comment by athul** [comment]
K
