### ISSUE TITLE
[UX] Improve filters

### ISSUE THREAD

**Issue by michellealva** [frappe/helpdesk#1339]
- Under "All Tickets" I see the following options

<img width="689" alt="image" src="https://github.com/frappe/helpdesk/assets/50285544/7da12729-825b-431d-aba7-ff76a920434f">

- Under the Status filter I see the following options

<img width="823" alt="image" src="https://github.com/frappe/helpdesk/assets/50285544/f9d0e1ef-c05a-40c4-947d-09fd045b9e43">

It's the same repetitive filters. Just show the Status filter and add Support Agent as a separate filter (?). That way I will be able to see combinations of open/closed tickets of all agents.

**Comment by ssiyad** [comment]
First one is preset filters. Second is for status only. I believe they're both important. The placement could be improved though

**Comment by michellealva** [comment]
@ssiyad I don't think the preset filter is needed if it has to just show tickets that are assigned to me.

If that's its only purpose, then change that filter to Agent and show me a list of agents including myself so that I can use a combination of Status + Agents to get the tickets.
