### ISSUE TITLE
Custom email pull may not be required

### ISSUE THREAD

**Issue by ankush** [frappe/helpdesk#1401]
Framework by default does this, why is separate hook required?

https://github.com/frappe/helpdesk/blob/7ca038501da4f984d43393f35d6a09dcacd828af/helpdesk/overrides.py#L4-L14

Also this cron doesn't appear to be valid, what does it mean?

https://github.com/frappe/helpdesk/blob/7ca038501da4f984d43393f35d6a09dcacd828af/helpdesk/hooks.py#L29

**Comment by ssiyad** [comment]
A relic from the past, used to increase pull frequency. Can be removed
