### ISSUE TITLE
Single Ticket Display error

### ISSUE THREAD

**Issue by Shivam327** [frappe/helpdesk#1408]
![image](https://github.com/frappe/helpdesk/assets/23412311/5e838325-f6ae-403a-a094-b5dbec73334e)

Before update it use to show the Details.

**Comment by Shivam327** [comment]
> @Shivam327 check if someone is assgined?

ticket was created from new ticket button

**Comment by Shivam327** [comment]
> v14? Looks like there are some mismatches between contacts in v14 and v15

Yes Frappe V14

**Comment by Shivam327** [comment]
When I Comment QBContact.full_name 
![image](https://github.com/frappe/helpdesk/assets/23412311/6e5c7576-68d1-4759-86b2-3aa79fcb8056)

Ticket is visible
![image](https://github.com/frappe/helpdesk/assets/23412311/8e288fb2-f118-4bb2-8161-14f626a15744)

**Comment by ssiyad** [comment]
@Shivam327 Test and raise a PR?

**Comment by Shivam327** [comment]
> @Shivam327 Test and raise a PR?

@ssiyad Done Raised a PR please check
