### ISSUE TITLE
Data is Empty for Ticket History

### ISSUE THREAD

**Issue by Shivam327** [frappe/helpdesk#1432]
Nothing is shown in Ticket History.

![image](https://github.com/frappe/helpdesk/assets/23412311/40e59193-9a9c-464c-8487-3609c8e4bbd7)
![image](https://github.com/frappe/helpdesk/assets/23412311/65ea371c-d706-4b18-b126-25c63949311f)

**Comment by ssiyad** [comment]
Any error? What does API response say? Provide more context

**Comment by Shivam327** [comment]
I have checked the console. 
Its Clean. No errors in console

**Comment by ssiyad** [comment]
Is there anything `HD Ticket Activity`?

**Comment by Shivam327** [comment]
Yes, I changed Status, priority everything

**Comment by Shivam327** [comment]
IF user is admin and not added as agent, no data will be shown to user.
