### ISSUE TITLE
Administrator not able to view tickets

### ISSUE THREAD

**Issue by niraj2477** [frappe/helpdesk#1433]
Administrator is not able to view the tickets in the portal view.
<img width="1457" alt="Screenshot 2023-08-03 at 4 58 00 PM" src="https://github.com/frappe/helpdesk/assets/28840468/1a286663-9426-43b6-a3d1-b1fb57dbecb8">

- Upon inspecting this was the query being genrated.
```
SELECT *,(SELECT COUNT(*) FROM `tabHD Ticket Comment` WHERE `tabHD Ticket Comment`.`reference_ticket`=`tabHD Ticket`.`name`) `count_comment`,(SELECT COUNT(*) FROM `tabCommunication` WHERE `tabCommunication`.`reference_doctype`='HD Ticket' AND `tabCommunication`.`reference_name`=`tabHD Ticket`.`name`) `count_communication` FROM `tabHD Ticket` WHERE `contact`='Administrator' OR `customer`=NULL OR `raised_by`='Administrator' ORDER BY `modified` DESC,`modified` DESC LIMIT 20
```

- Ideally, `Administrator` should be able to view all the tickets by default.

**Solution** 
- Check if current user is `Administrator`, based on that set the filters.

**Comment by ssiyad** [comment]
I do understand the problem, but handling edge cases like this will introduce more problems. We can consider this later. But right now its better not to use admin account for Helpdesk (it is generally not recommended to use Admin account)
