### ISSUE TITLE
Addition of Filters Customer Portal

### ISSUE THREAD

**Issue by Shubee10** [frappe/helpdesk#1439]
The current portal does not have any provision to add filters. The filters are limited to open & closed tickets only. The necessary filters on the portal are as mentioned below: 

- Need company filter to get company wise issue list
- Need filter for subject
- Need filter on the basis of ticket id

**Comment by ssiyad** [comment]
> Need company filter to get company wise issue list

Helpdesk does not support `Company`. So I don't get what you mean by this

**Comment by michellealva** [comment]
@ssiyad company as in customer company

**Comment by michellealva** [comment]
closed via https://github.com/frappe/helpdesk/pull/1428
