### ISSUE TITLE
Cannot access my erpnext account 

### ISSUE THREAD

**Issue by Al-Fataire** [frappe/helpdesk#1459]
Kindly help in resolving this 
![28074049-33a7b134-661d-11e7-9be1-063999216a56](https://github.com/frappe/helpdesk/assets/94943010/6eed7ca7-149b-4f99-89e5-a63296dfd136)

**Comment by Al-Fataire** [comment]
Account Zangibrands.erpnext.com

**Comment by ssiyad** [comment]
This is repo for the app `Helpdesk`, not helpdesk of Frappe
