### ISSUE TITLE
Issue in description box size on New Helpdesk

### ISSUE THREAD

**Issue by smbcatalyst** [frappe/helpdesk#1492]
When we try to type massage, we are facing the issue as space restrictions. It is getting difficult to type 4-5 lines in issue or reply. Kindly allow more space to write the issue. (Check both Old portals)

![image](https://github.com/frappe/helpdesk/assets/113963271/aec1a314-7de1-4b16-b983-ecb393ff6c2c)

**Comment by ssiyad** [comment]
Has been fixed in https://github.com/frappe/helpdesk/pull/1486. Try updating if you haven't already. If it is latest, try clear cache of your browser

**Comment by ssiyad** [comment]
FYI: Text editors start with a minimum height. But they will expand upto a point as you input text

**Comment by smbcatalyst** [comment]
Hi,

Request not to close issue until we confirm. It is difficult to type as on pasting any screenshot, we get very less space to enter details. We request to check old portals to get clear idea.

**Comment by ssiyad** [comment]
> We request to check old portals to get clear idea.
What do you mean? Are you talking about a specific instance? If so, can you share the url?
