### ISSUE TITLE
Ticket can be resolved without any Resolution Remarks

### ISSUE THREAD

**Issue by itsbalpreet** [frappe/helpdesk#1502]
Agent is able to set ticket status as resolved without any resolution comment. Like there is a resolution detail section in Doc type screen, the same should provided in the Agent Log in too.

**Comment by ssiyad** [comment]
> Agent is able to set ticket status as resolved without any resolution comment
Agents can leave an internal comment no?

**Comment by itsbalpreet** [comment]
Internal comment is not for customer right? If I am resolving the ticket without giving any update to customer is that correct??

**Comment by ssiyad** [comment]
In that case, you can send a response before marking as resolved?

**Comment by itsbalpreet** [comment]
Tool should enforce providing a response. If you leave it to a person's discretion they will not put resolution comments while closing the ticket. Hence this ask. So many other HelpDesk tool have this function

**Comment by RitvikSardana** [comment]
You can have this as a customisation and some server script.
