### ISSUE TITLE
Need to show latest reply first on opening issue

### ISSUE THREAD

**Issue by smbcatalyst** [frappe/helpdesk#1504]
Need to show latest reply first when we open any old issue. Everytime scrolling down is unnecessarily taking time. If an issue has long conversations, an user has to scroll till last reply. Kindly do the needful.

<img width="1062" alt="image" src="https://github.com/frappe/helpdesk/assets/113963271/54731458-11aa-4733-a222-d1bb5f7a0df6">
As shown i above screenshot, we need to scroll down to read latest reply.

**Comment by michellealva** [comment]
@ssiyad maybe you can auto-scroll to the bottom of the page (latest reply) by default.

**Comment by smbcatalyst** [comment]
Hi, Try to show it first as it was available on previous both portals.

**Comment by ssiyad** [comment]
https://github.com/frappe/helpdesk/pull/1535
