### ISSUE TITLE
On Hold status in HD Ticket

### ISSUE THREAD

**Issue by jecinthamary** [frappe/helpdesk#1542]
We wish to have the On Hold status be included in Frappe Help desk ticket status.   This value is available in the support issues module of ERP Next.   The On Hold status will be helpful for pausing the SLA while we have a third party dependency to resolve the ticket.

Version:
ERP Next: v14.36.0 (version-14)
Frappe Framework: v14.46.0 (version-14)
Helpdesk: v0.10.0 (main)

**Comment by ssiyad** [comment]
It is included as `Paused`

**Comment by jecinthamary** [comment]
Thank you for the prompt reply.  

    When Ticket Status is set to replied both response and resolution SLA gets fulfilled.  Expectation is only Response needs to be fulfilled.
     Also is there a way without changing the status of the ticket to Pause the ticket’s SLA.

Following are the steps for recreation.   
1) Help Desk SLA was set as Default

Response and Resolution
  Priority - Urgent - First response time - 15 minutes   - Resolution time - 1 hour
  Priority - High - First response time - 1 hour - Resolution time - 4 hour
  Priority - Medium - First response time - 1 hour - Resolution time - 8 hour
  Priority - Low - First response time - 4 hour - Resolution time - 16 hour

Status Fulfilled
Status - Resolved, Replied
SLA Paused on
 Not Set
Working Hours
Monday to  Friday
Start time - 09:00     End time - 18:30

2) New ticket of priority "Low" is raised
Status - Open
Agreement status - label dispplayed as "First Response due"
First Response - in 4 hrs
Resolution - in 2 days

3) The Help desk Administrator  changes the ticket types (accordingly Priority of the ticket is set), ticket priority is not changed, and assigns a agent.

4) The assigned agent sends a "Response"  to the ticket.  Expectation - Ticket status to be changed to  "Replied" but doesn't change
Status - Open
Agreement status - label displayed as "First Response due"
First Response - Fulfilled
Resolution - in 2 days

5) The assigned agent changes the status to "Replied"
Status - Replied
Agreement status - Fulfilled
First Response - Fulfilled
Resolution - Fulfilled

 
PFA:
![image](https://github.com/frappe/helpdesk/assets/126246621/a56618e9-9a0f-42a2-b4ae-14fa04c9d20a)

**Comment by ssiyad** [comment]
Can I know which version/commit of Helpdesk you have? SLA has been refactored recently. Please update and check if this issue is still present

**Comment by ssiyad** [comment]
> The assigned agent sends a "Response" to the ticket. Expectation - Ticket status to be changed to "Replied"

This is expected, as not every response is meaningful

**Comment by jecinthamary** [comment]
When Ticket Status is set to replied, Resolution SLA also gets fulfilled.  Expectation is only Response needs to be fulfilled.
 Also is there a way without changing the status of the ticket, to Pause the ticket’s SLA.

**Comment by jecinthamary** [comment]
On creation of HD Service level agreement SLA Fulfilled on mandatory but there is no table here

![image](https://github.com/frappe/helpdesk/assets/126246621/0e9e3b41-1780-4805-99b2-ab143ad6c8f3)

**Comment by ssiyad** [comment]
Seems like the DocType is corrupted. Can you force reload the doctype? (Search for `frappe.reload_doctype`

**Comment by jecinthamary** [comment]
'SLA Fulfilled On' table have display depend on condition 'document_type'. Here there is no field name as document_type, please review the doctype

**Comment by ssiyad** [comment]
You are right. `document_type` is an old field and not required anymore. I removed it in https://github.com/frappe/helpdesk/pull/1544

**Comment by jecinthamary** [comment]
> When Ticket Status is set to replied, Resolution SLA also gets fulfilled. Expectation is only Response needs to be fulfilled. Also is there a way without changing the status of the ticket, to Pause the ticket’s SLA.

**Comment by jecinthamary** [comment]
When Ticket Status is set to replied, Resolution SLA also gets fulfilled. Is this correct?

**Comment by ssiyad** [comment]
> When Ticket Status is set to replied, Resolution SLA also gets fulfilled. Is this correct?

No. can you share a recording of this happening? Share your SLA too

**Comment by jecinthamary** [comment]
Please refer the below screen shots, SLA Paused on is not set.  But when status changed from open to replied, resolution shows as fulfilled
![image](https://github.com/frappe/helpdesk/assets/126246621/8df2c22a-9d91-497e-91ea-0699d752b739)
![image](https://github.com/frappe/helpdesk/assets/126246621/6db086ad-466d-4c21-8127-87a8bd71264f)

**Comment by ssiyad** [comment]
This should be fixed now. However if you don't have a `SLA paused on` status, the replied status won't be set. This is because the logic relies on this field. This indeed is a problem though. Please open another issue for that
