### ISSUE TITLE
Doctype Ticket Priority not found

### ISSUE THREAD

**Issue by jecinthamary** [frappe/helpdesk#1552]
Helpdesk 0.10.0

1.Ticket Summary Report

When I set the "Ticket Priority" filter in this report, an exception is thrown.
"Doctype ticket Priority not found"
When looking in the doctype list , there is a HD Ticket Priority.
.
2.First Response Time for Tickets Report

pymysql.err.ProgrammingError: (1146, "Table 'erphns.tabTicket' doesn't exist")

Doctype name should be 'HD Ticket'

**Comment by sumitbhanushali** [comment]
fixed in https://github.com/frappe/helpdesk/pull/1723, https://github.com/frappe/helpdesk/pull/1703
