### ISSUE TITLE
restart failed: Couldn't find supervisorctl in PATH

### ISSUE THREAD

**Issue by checkin247** [frappe/helpdesk#1553]
frappe 5.17.1 with docker container

`bench get-app helpdesk`
then, after the build command, I get 

```
Done in 16.28s.
WARN: restart failed: Couldn't find supervisorctl in PATH
```

installing the app with bench won't work (`bench --site sitename install-app helpdesk`). It actually makes the scheduler container exit with "ModuleNotFoundError: No module named 'helpdesk'"
I manually removed the "helpdesk" app.
Then I tried to installing supervisorctl into the docker container and run `bench get-app helpdesk` again, then I get 

```
Done in 16.01s.
$ supervisorctl restart frappe:
unix:///var/run/supervisor.sock no such file
WARN: restarting supervisor failed. Use `bench restart` to retry.
```
I tried it in a fresh site (`new-site`) as well as an existing with a fresh erpnext app.

please advise

**Comment by asharamseervi** [comment]
+1. I have faced the exact same with docker on MacBook M2 Pro.

**Comment by littletuna4** [comment]
@asharamseervi I worked it out, (at least partly). You can't use some of the bench commands in the dockerised version. You have to install the apps in a custom docker image, and then spin it back up.

**Comment by mgnanaprakash11** [comment]
bench restart also not working inside docker.
