### ISSUE TITLE
SLA Pause not working

### ISSUE THREAD

**Issue by jecinthamary** [frappe/helpdesk#1554]
1. SLA hold -  
Pause SLA feature is not working.   “Helpdesk SLA”  has been configured to Pause SLA for Ticket status Replied, but even after ticket is set to Replied and the ticket agreement status is shown as “Paused” the SLA is ticking in the background.  When ticket status is set to Open from replied the SLA Resolution hours shown is the one that got assigned at the time of ticket raising.

2.Priority of the ticket is set based on the ticket type and not modifiable by the agent.

**Comment by ssiyad** [comment]
> Priority of the ticket is set based on the ticket type and not modifiable by the agent.

Please create different issues for different things. Also, please explain in detail
