### ISSUE TITLE
Error while creating ticket from Agent Portal

### ISSUE THREAD

**Issue by asoral** [frappe/helpdesk#1561]
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1622, in call
    return fn(*args, **newargs)
  File "apps/helpdesk/helpdesk/helpdesk/doctype/hd_ticket_template/api.py", line 17, in get_one
    found, about = frappe.get_value(DOCTYPE_TEMPLATE, name, ["name", "about"])
TypeError: cannot unpack non-iterable NoneType object

**Comment by asoral** [comment]
Cannot read properties of undefined (reading 'filter')

**Comment by ssiyad** [comment]
Can you share a screenshot/recording/payload? `name` is either missing or the template does not exist

**Comment by asoral** [comment]
![image](https://github.com/frappe/helpdesk/assets/11851156/bf73ea3d-c89d-4d80-8a2d-8f20d7790cb3)

**Comment by ssiyad** [comment]
@asoral what is the payload? You can see that in request (network tab)

**Comment by asoral** [comment]
The error is when there is no ticket template of name Default. I created one manually and got it resolved for now.
But couldn't understand why would that be a validation

**Comment by HishamDF** [comment]
I have the same problem

![image](https://github.com/frappe/helpdesk/assets/118101928/b3db4590-b029-4279-8799-5ea00dc77121)

Network Tab:

![Uploading image.png…]()

**Comment by Karam-Qutran** [comment]
I encountered an issue upon opening the Frappe Helpdesk for the first time after installation. When I clicked on "New Ticket," I received the following error messages:

"TypeError: Internal Server Error"

Upon attempting to submit a new ticket, the error message "A.value is undefined" was displayed.

this the console log

POST
http://127.0.0.1:8000/api/method/helpdesk.helpdesk.doctype.hd_ticket_template.api.get_one
[HTTP/1.1 500 INTERNAL SERVER ERROR 18ms]

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1701, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/helpdesk/helpdesk/helpdesk/doctype/hd_ticket_template/api.py", line 17, in get_one
    found, about = frappe.get_value(DOCTYPE_TEMPLATE, name, ["name", "about"])
TypeError: cannot unpack non-iterable NoneType object



the payload request 
 
name:"Default"

![Screenshot 2024-02-05 045249](https://github.com/frappe/helpdesk/assets/110362095/9fa85990-dd18-471b-ad4a-4a54110274d3)

**Comment by rajamuppidi** [comment]
Experiencing the same issue, did you find any solution ?? When I clicked on "New Ticket," I received the following error messages:

"TypeError: Internal Server Error"

**Comment by Karam-Qutran** [comment]
> Experiencing the same issue, did you find any solution ?? When I clicked on "New Ticket," I received the following error messages:
> 
> "TypeError: Internal Server Error"

To resolve this issue, 
navigate to doctype > Ticket Template, 
then create a new Ticket Template named "Default"
 and it should function properly.

**Comment by rajamuppidi** [comment]
I have added the said default template when i click new ticket and submit a ticket its now getting Internal Server Error popup message

**Comment by Karam-Qutran** [comment]
> I have added the said default template when i click new ticket and submit a ticket its now getting Internal Server Error popup message


after adding new Ticket Template named "Default"

add 
doctype >HD Ticket Type
 
![image](https://github.com/frappe/helpdesk/assets/110362095/32df8409-3480-4f0f-b122-72b95ad0e234)

doctype >HD Preset Filter


![image](https://github.com/frappe/helpdesk/assets/110362095/51e742e3-60b0-4b2b-a278-31f56c0a51b5)

and add any think in HD Service Level Agreement
like 
![image](https://github.com/frappe/helpdesk/assets/110362095/7a77540d-0576-438f-9a36-7ac97b068fea)

**Comment by Karam-Qutran** [comment]
doctype >HD Preset Filter


![image](https://github.com/frappe/helpdesk/assets/110362095/e448435b-bceb-4875-a210-5b00f62516c7)
![image](https://github.com/frappe/helpdesk/assets/110362095/5e0fb043-716b-4059-aa04-71905f029472)
![image](https://github.com/frappe/helpdesk/assets/110362095/ee092ce5-f4c5-4669-aa67-df99228a5baf)
![image](https://github.com/frappe/helpdesk/assets/110362095/70a9600a-1aae-4507-bec5-ca68e79a03a2)
![image](https://github.com/frappe/helpdesk/assets/110362095/b40ee456-a178-48c8-a113-5b8309c0f3eb)

**Comment by rajamuppidi** [comment]
I have added all the doc mentioned, but still getting the same kind of error

![Screenshot 2024-03-18 at 6 47 15 PM (2)](https://github.com/frappe/helpdesk/assets/122896172/a36a9a0e-71a0-4a02-87a0-7ad9b6ee17f9)

Please help

**Comment by RitvikSardana** [comment]
should be fixed now, re-open if the issue still persists
