### ISSUE TITLE
Reduce space between two lines in the reply/comment

### ISSUE THREAD

**Issue by surajshetty3416** [frappe/helpdesk#1564]
![Screenshot 2023-09-18 at 1 16 24 PM](https://github.com/frappe/helpdesk/assets/13928957/69a8cc47-cc21-4435-be0f-9c763f52a8ff)

It gets confusing if extra line has been added or not.

**Comment by Cellhitch** [comment]
same as #1641

**Comment by RitvikSardana** [comment]
Is this part of old helpdesk @surajshetty3416 ??
