### ISSUE TITLE
Error in Ticket submit 

### ISSUE THREAD

**Issue by AlaaBadry** [frappe/helpdesk#1565]
We got this error when submit ticket in self hosted its working normally in frappe cloud 
![Screenshot Capture - 2023-09-20 - 01-45-06](https://github.com/frappe/helpdesk/assets/26534497/fd72f8f1-02d4-4d29-9f87-307940ca3bc4)

**Comment by ssiyad** [comment]
Please post full error traceback. You could find it in `console` tab

**Comment by AlaaBadry** [comment]
It solved by created HD template
