### ISSUE TITLE
Screen not showing anything after adding canned response.

### ISSUE THREAD

**Issue by Shivam327** [frappe/helpdesk#1566]
![image](https://github.com/frappe/helpdesk/assets/23412311/dcfe109f-b5e6-423f-b715-cb5e17d8e949)

I have added canned response, after clicking on add response, its showing blank screen.
Below is the URL
![image](https://github.com/frappe/helpdesk/assets/23412311/6bad7334-85e2-41f5-b8d4-0f4c40c3ac0c)

Thou its getting added and new response is shown below in list
![image](https://github.com/frappe/helpdesk/assets/23412311/2ac7a7e4-8fbe-4c2a-8675-08a33f7bad69)

Also just a suggestion: Please look at the colour of the Save Button. Can we it primary button and change text to save canned response ?

**Comment by Karam-Qutran** [comment]
to solve this 
got to /frappe-bench/apps/helpdesk/desk/src/components/desk/global  edit this file  AddNewCannedResponsesDialog.vue

line 203 in this function  
resources: {
		newResponse() {
			return {
				url: "frappe.client.insert",
				onSuccess: (doc) => {
					this.$router.push(
						`/settings/canned_responses/${doc.name}`
					)
				},
				

change the routing to

	`/canned-responses/${doc.name}`
				

and the color of button .
 in the same file
 line 52
 				<Button
				        theme="gray"
                                        variant="solid"
					appearance="primary"
					@click="addResponse()"
					
					
![image](https://github.com/frappe/helpdesk/assets/110362095/368f367b-03a5-4682-b075-3358f3779e72)

![image](https://github.com/frappe/helpdesk/assets/110362095/f9a83b54-2680-4aab-93bb-9ac5782e5dc9)
