### ISSUE TITLE
Ticket List Not showing any ticket text (Subject)

### ISSUE THREAD

**Issue by Shivam327** [frappe/helpdesk#1569]
![image](https://github.com/frappe/helpdesk/assets/23412311/4cf070c8-f222-4b62-a88d-cad02782cc35)
![image](https://github.com/frappe/helpdesk/assets/23412311/9ff1abe4-f5b3-4c71-8a97-436badcf0020)

**Comment by ssiyad** [comment]
Check console and post any relevant info

**Comment by RitvikSardana** [comment]
should be fixed now, re-open if the issue still persists
