### ISSUE TITLE
Error in sending email

### ISSUE THREAD

**Issue by alishk7193** [frappe/helpdesk#1570]
facing below error in notifications in helpdesk. I am able to recieve ticket replies but not getting any notifications from the system like (ticket update, state change, priority change etc.)

Traceback with variables (most recent call last):
  File "apps/frappe/frappe/utils/background_jobs.py", line 202, in execute_job
    retval = method(**kwargs)
      site = 'frappe.helpdesk'
      method = <function send_mail at 0x7f68b4c99bd0>
      event = None
      job_name = '<function send_mail at 0x7f68b784a680>'
      kwargs = {'email_queue_name': 59, 'dedupicate': True}
      user = 'Administrator'
      is_async = True
      retry = 0
      retval = None
      method_name = 'send_mail'
      before_job_task = 'frappe.monitor.start'
builtins.TypeError: send_mail() got an unexpected keyword argument 'dedupicate'

I have checked the backgroud_jobs.py and there is no argument 'dedupicate'. originally its 'deduplicate'. Please help

**Comment by ssiyad** [comment]
Notifications for updates is an upcoming feature. It is not there yet. However you can use server scripts (with doctype events) to have a temporary solution. Also, I don't get where this error comes from. What version of Frappe framework are you using?

**Comment by alishk7193** [comment]
I tried using the server scripts but the error is same.

**Comment by RitvikSardana** [comment]
should be fixed now, re-open if the issue still persists
