### ISSUE TITLE
Issue in Creating Ticket in Incoming E-mail

### ISSUE THREAD

**Issue by rajatnesto** [frappe/helpdesk#1571]
Version: 
**Frappe Framework: v14.43.0 (HEAD)**
**Helpdesk: v0.10.0 (HEAD)**

I have made configuration in my HelpDesk for creating ticket in HD Ticket whenever I receive email at my support email address.
This used to work in the initial version of FrappeDesk.

The same have worked in my local instance and the changes that were made to make it the work is, 
- Setup Email Account for Incoming E-mail
- Add IMAP details for Incoming E-mail
- In User (Admin) added Email Section with E-mail Account for receiving email.

The site is hosted in Frappe Cloud and have raised a ticket over there as well.

**Comment by rajatnesto** [comment]
https://ibb.co/12jTNr2
https://ibb.co/HKwKWxR

please check these images, I have added

**Comment by RitvikSardana** [comment]
should be fixed now, re-open if the issue still persists
