### ISSUE TITLE
Socket Connection Error in Agent and Customer Portal launch

### ISSUE THREAD

**Issue by shubhendu77** [frappe/helpdesk#1576]
I guess latest development around Notification has some issue related to Socket Connection. I have updated app yesterday and since then it is giving socket connection error and it appears continuously for 4 -5 times. This is happening in Agent and Customer Portal both.

<img width="909" alt="image" src="https://github.com/frappe/helpdesk/assets/47205652/ba7b5488-b87a-4caa-adc9-8b17b15a23ec">

console screenshot

<img width="960" alt="image" src="https://github.com/frappe/helpdesk/assets/47205652/d95172fb-4501-46c7-8090-f48d6b4b80c0">

Kindly check.

**Comment by ssiyad** [comment]
https://github.com/frappe/helpdesk/pull/1578
