### ISSUE TITLE
tickets not opened upgrading the version from 0.9.1 to 0.10.0 

### ISSUE THREAD

**Issue by prasathsekar** [frappe/helpdesk#1577]
Upgrading the Frappe Helpdesk version from 0.9.1 to 0.10.0, I can see the list of tickets; however, when selecting any ticket, the screen remains blank.

I have attached a screenshot of the error for your reference.

![Screenshot 2023-09-30 at 5 56 31 PM](https://github.com/frappe/helpdesk/assets/25291469/c844fa86-9ccd-4a18-b9b3-d240228a9e10)

**Comment by ssiyad** [comment]
Can you post full error traceback? This does not look complete

**Comment by prasathsekar** [comment]
![Uploading Screenshot 2023-10-04 at 4.09.49 AM.png…]()

**Comment by ssiyad** [comment]
`is_pinned` must be present. Did you try `migrate`?

**Comment by prasathsekar** [comment]
No, we have not tried to migrate. Need to Upgrade the helpdesk.

**Comment by ssiyad** [comment]
> Upgrading the Frappe Helpdesk version from 0.9.1 to 0.10.0

Meaning you're upgrading right?

**Comment by prasathsekar** [comment]
Yes.

**Comment by prasathsekar** [comment]
Any Work around for the above issue ?

**Comment by JoSoG89** [comment]
> Any Work around for the above issue ?


Suppost to be fixed before #1586

but im still the same problem
