### ISSUE TITLE
Notification Email to Agent on Reply from Customer

### ISSUE THREAD

**Issue by prasathsekar** [frappe/helpdesk#1580]
Currently, whenever a ticket is assigned to an agent, they receive an email notification. However, after sending a reply to the customer, if the customer responds to the ticket, the status changes from 'Replied' to 'Open' without triggering any notification.

Now, the agent who is working on other tasks does not know that they have an open ticket.

Is there any workaround for this issue?

**Comment by sumitbhanushali** [comment]
in app notification when ticket reopens -> https://github.com/frappe/helpdesk/pull/1719

email for every notification will be too much, grouping unread notifications will be better.
I have raised separate issue for this https://github.com/frappe/helpdesk/issues/1724
