### ISSUE TITLE
on login helpdesk

### ISSUE THREAD

**Issue by HishamDF** [frappe/helpdesk#1581]
Socket Connection Error
xhr poll error

**Comment by ssiyad** [comment]
Can you please share some context? Frappe/Helpdesk version etc?

**Comment by yasser1248** [comment]
same error xhr poll error

**Comment by malnozili** [comment]
Helpdesk: v0.10.0 (version-14)

**Comment by Dhruvang-cyg** [comment]
i am facing the same error with same versions of apps
**ERPNext: v15.8.0 (version-15)
Frappe Framework: v15.7.0 (version-15)
_Helpdesk: v0.10.0 (version-14)_
Frappe HR: v15.7.0 (version-15)**

**Comment by RitvikSardana** [comment]
fixed via https://github.com/frappe/helpdesk/pull/1906
