### ISSUE TITLE
Unable to create Ticket on Receiving Emails

### ISSUE THREAD

**Issue by rajatnesto** [frappe/helpdesk#1582]
**Frappe Framework**: v14.43.0 (HEAD)
**Helpdesk:** v0.10.0 (HEAD)

Issue with ticket creation in Frappe Cloud.

Have setup Email Account for Incoming and Outgoing both, till the previous version was able to create ticket when receiving emails on the email account setup in Frappedesk.
But since we have migrated to new version HelpDesk, the ticket creation has stopped working.
The same has been tried and tested on local and hosted instance on other servers as well.
What can be the issue and what I need to handle if I want HelpDesk to work with ticket creation on receiving email in Frappe Cloud.

**Comment by ssiyad** [comment]
Please share a (full) screenshot of your 'Email Account` setup

**Comment by rajatnesto** [comment]
https://ibb.co/12jTNr2
https://ibb.co/HKwKWxR

please check these images, I have added

**Comment by rajatnesto** [comment]
<img width="960" alt="Admin Email" src="https://github.com/frappe/helpdesk/assets/120168522/b213c7f7-61c7-4b45-9221-4f93e86f97ba">
![Screenshot 2023-10-31 104834](https://github.com/frappe/helpdesk/assets/120168522/91668956-e118-4b81-a83a-0f1a85a5e85c)

**Comment by rajatnesto** [comment]
![Screenshot 2023-10-31 104834](https://github.com/frappe/helpdesk/assets/120168522/7a473c7e-ea72-4e41-a4e0-631c6e77b10c)

**Comment by agrawalshubham01** [comment]
@rajatnesto Not sure, but you may try to change Folder Name to **Inbox** instead of INBOX as this works fine by me. Also you may check google does provide limited number of api calls.

**Comment by RitvikSardana** [comment]
should be fixed now, re-open if the issue still persists

**Comment by i-am-vimal** [comment]
> [@rajatnesto](https://github.com/rajatnesto) Not sure, but you may try to change Folder Name to **Inbox** instead of INBOX as this works fine by me. Also you may check google does provide limited number of api calls.

Can anyone confirm if this worked?
