### ISSUE TITLE
Socket Error

### ISSUE THREAD

**Issue by littletuna4** [frappe/helpdesk#1584]
Hi all,
I've just installed helpdesk on my instance but get
`Socket Connection Error: Invalid origin`
popping up.
Does anyone have a solution/suggestion/idea?

v14 docker_frappe with custom image

**Comment by littletuna4** [comment]
I have fixed this by renaming the site directory from `frontend` to `mydomain.com` and adding a `"host_name" : "mydomain.com"` field in the sites_config.json file in sites/mydomain.com directory

**Comment by MuhammadNaeem42** [comment]
i unable to fix this socket issue please help 

> I have fixed this by renaming the site directory from `frontend` to `mydomain.com` and adding a `"host_name" : "mydomain.com"` field in the sites_config.json file in sites/mydomain.com directory

**Comment by NirajRegmi** [comment]
Made changes as per your suggestion but getting same issue. These are the versions of my instances.

<img width="230" alt="image" src="https://github.com/frappe/helpdesk/assets/47034619/09cc90e9-7624-480a-bce1-ed57ca35819e">

**Comment by coela-oss** [comment]
I faced same issue and solved it with `bench add-to-hosts` in version-15.
