### ISSUE TITLE
Logo and Favicon upload not working in docker environment.

### ISSUE THREAD

**Issue by littletuna4** [frappe/helpdesk#1589]
Hi there,
Anyone have any insight into whether the logo and favicon uploads work for a frappe_docker instance? It looks at least for the logo, that it is made at build, and I'm aware that frappe_docker isn't compatible with `bench build`?
Thanks in advance.

**Comment by benisrael29** [comment]
I'm experiencing the same issue. @littletuna4 have you found a fix?

**Comment by RitvikSardana** [comment]
fixed via https://github.com/frappe/helpdesk/pull/1937
