### ISSUE TITLE
Sign-Up Success Message/Redirect

### ISSUE THREAD

**Issue by littletuna4** [frappe/helpdesk#1599]
Hi there,
As demonstrated in the below gif. There is no indication that an account has successfully been created or that the new user should expect an email. Additionally, the user is not redirected to login. Anyone able to make this change (or have any advice as to how I could make pull request with such a change made)?

![ezgif com-video-to-gif](https://github.com/frappe/helpdesk/assets/108212671/32a6c925-5b1b-4490-8882-44e6da9360c1)

**Comment by frankymcgee** [comment]
I am also having the exact issue. There is no prompt at all to tell the user to check their emails.

**Comment by RitvikSardana** [comment]
fixed via https://github.com/frappe/helpdesk/pull/1906
