### ISSUE TITLE
First response due for tickets that are marked as resolved

### ISSUE THREAD

**Issue by ankush** [frappe/helpdesk#1607]
![image](https://github.com/frappe/helpdesk/assets/9079960/255e9cba-c18d-4566-ba50-d51deb81cfe5)

When setting resolution time, first response can also be set as same. 

Use case:
- Internal tickets where there isn't going to be a reply and just get closed once completed.

**Comment by michellealva** [comment]
@ssiyad is this fixed?

**Comment by ankush** [comment]
yep iirc
