### ISSUE TITLE
incorrect filter value

### ISSUE THREAD

**Issue by ankush** [frappe/helpdesk#1608]
if you set filters to "My open tickets", nothing shows up in "assigned" column. 

![image](https://github.com/frappe/helpdesk/assets/9079960/ea4452cd-7e17-4926-98d6-0dec1441daef)

**Comment by michellealva** [comment]
@ssiyad could you please take this up on priority?

**Comment by michellealva** [comment]
@ssiyad please fix this ASAP. I am unable to filter tickets.

**Comment by sumitbhanushali** [comment]
fixed in https://github.com/frappe/helpdesk/pull/1704
