### ISSUE TITLE
Tickets not visible for agent if there are also an customer

### ISSUE THREAD

**Issue by cwerner1** [frappe/helpdesk#1616]
Hi 

I've Problems with the visibility of tickets for agents. 
Setup: I installed helpdesk to an existing erpnext installation.
I created a new Agent with the mail agent@example.com.
This user already exists as Customer and as Lead.

Now I only get the Tickets from this user and LEAD and not seeing all Tickets.

So far I located this problem to this Place
https://github.com/frappe/helpdesk/blob/3f99ef857e15b49d12737fc34ad1416233e88dfb/helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py#L86
`Line 73 function get_list_filters(`

`Line 86: get_customer(user)`

In the next line the query Condition for the currently user in the session get assigned. 
it ignores if the user is an agent.

Setup:

1. running ERP Installation
2. setup an Lead Or new Customer with the mail mail@example.com
3. install helpdesk
4. create an agent with the mail mail@example.com
5. Create a new Ticket. 
6. In the helpdesk Ticket views no Tickets are visible.
7. comment line 86 and 87 in hd_ticket.py   => all Tickets are Visible

**Comment by RitvikSardana** [comment]
should be fixed now, re-open if the issue still persists
