### ISSUE TITLE
bug: reply to ticket stopped from mobile view 

### ISSUE THREAD

**Issue by ashish-greycube** [frappe/helpdesk#1619]
Earlier we were able to reply to tickets from mobile chrome browser , but unable to do so now

Even tried to switch to desktop site mode in mobile. Still unable to reply.

![Screenshot_20231107-072604](https://github.com/frappe/helpdesk/assets/29812965/cae3c293-c005-4d40-baaf-7d73ad29d0c4)

**Comment by RitvikSardana** [comment]
Should be fixed with new customer portal
