### ISSUE TITLE
Wrong timezone for portal users

### ISSUE THREAD

**Issue by barredterra** [frappe/helpdesk#1621]
Assume I'm in Germany and the helpdesk is running in India.

When I create a support ticket, I will see "in 4 hours" as the creation time, because Indian time is 4 hours ahead of German time. Four hours later, I will see "just now"; after 8 hours I will see "4 hours ago"; etc. etc.

![Bildschirmfoto 2023-11-07 um 17 24 47](https://github.com/frappe/helpdesk/assets/14891507/97a3b47e-1692-4e53-a434-78fdf9751110)

The system should first convert the timestamp to the user's timezone, then produce the human readable, relative time.

**Comment by barredterra** [comment]
Update: I'm still reporting issues from the future 😎 ⚡

**Comment by sumitbhanushali** [comment]
@barredterra thanks for the reminder....will pick this issue on priority
