### ISSUE TITLE
502 Bad Gateway error after installing helpdesk

### ISSUE THREAD

**Issue by pranavkarimbam** [frappe/helpdesk#1625]
Hi,

 have ERPNext installed on my server, and I attempted to install Helpdesk on the same server using Bench. However, after the installation, the website does not load and shows a 502 Bad Gateway error. On the other hand, the ERPNext application is working without any problems. Could you please let me know if there are additional steps that need to be taken, aside from those mentioned in the GitHub documentation?

**Comment by RitvikSardana** [comment]
should be fixed now, re-open if the issue still persists
