### ISSUE TITLE
User access permission issue

### ISSUE THREAD

**Issue by HishamDF** [frappe/helpdesk#1628]
The permission of the users and access control are broken and the normal users like Customers can do the following:
• view tickets of other customers.
• view the list of all users and agents.
• edit personal information of all users on the system including admin and agent like changing email, profile pictures, and phone numbers

**By Security Team**

Please watch the video below

https://github.com/frappe/helpdesk/assets/118101928/d1b8154c-7406-420a-8959-d89e3cb6e925

**Comment by RitvikSardana** [comment]
should be fixed now, re-open if the issue still persists
