### ISSUE TITLE
Need Filters for Helpdesk Home Page

### ISSUE THREAD

**Issue by smbcatalyst** [frappe/helpdesk#1633]
We need few filters for better working and user friendly experience. We have already raised a ticket on Helpdesk (https://support.frappe.io/helpdesk/my-tickets/131) but there is progress on the issues. I think it is not time consuming or complex task. I hope this time it will not take time (already waited for 4 months).

![image](https://github.com/frappe/helpdesk/assets/113963271/09b73f45-5051-4d16-a8e4-0140d7429347)

Also, Kindly mention the request to get those issues in excel through export. All the mentioned functionality were available on last to last portal which was user friendly and upto expectations.

We require all these as any time we have to sit with client and update on each closed and open issues. As an implementation team we faces such issues. I hope the ERPNext will consider these points to make a stable and user friendly product.

**Comment by RitvikSardana** [comment]
fixed via new customer portal

**Comment by smbcatalyst** [comment]
Do we need to update the current app of need to install new app?

**Comment by RitvikSardana** [comment]
Just update, to latest version.
