### ISSUE TITLE
on_communication_update not implemented on frappe version-14

### ISSUE THREAD

**Issue by ovresko** [frappe/helpdesk#1646]
https://github.com/frappe/helpdesk/blob/6abdc36913a8765ea5bc64d7aabb59b4ec627e19/helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py#L716C11-L716C11

This part of HD Ticket (on_communication_update) does not work on frappe 14 it's part of frappe 15 on main branch not in 14. 

now status of ticket does not change to replied on response automatically , could go unnoticed.

**Comment by RitvikSardana** [comment]
does this issue still persists @ovresko ?

**Comment by ovresko** [comment]
yes, as long as you're using branch version-14 it's doesn't work, i've changed it manually in my code.
on_communication_update does not exist in frappe v14
https://github.com/frappe/frappe/blob/version-14/frappe/core/doctype/communication/communication.py
