### ISSUE TITLE
Team Selection Field Needed in Customer Portal Ticket Raising Dashboard

### ISSUE THREAD

**Issue by precihole** [frappe/helpdesk#1648]
We want team selection option while ticket raising as multiple team will going to raise issue using helpdesk in our case.
<img width="807" alt="image" src="https://github.com/frappe/helpdesk/assets/111174201/ebfd9e01-0d82-4b01-b928-e99f12cea3f0">

**Comment by RitvikSardana** [comment]
Can be done via HD Ticket Template DocType
