### ISSUE TITLE
Helpdesk Reports

### ISSUE THREAD

**Issue by jecinthamary** [frappe/helpdesk#1649]
1. Ticket Summary
2. Ticket Analytics
3. First Response Time for Tickets

Please review the above reports, and should be updated as per help desk doctype.

ex:
![image](https://github.com/frappe/helpdesk/assets/126246621/2dba23b5-cea7-48f5-8158-b7d1ab2b0db9)
Ticket Type->HD Ticket Type

**Comment by sumitbhanushali** [comment]
fixed in https://github.com/frappe/helpdesk/pull/1723, https://github.com/frappe/helpdesk/pull/1703
