### ISSUE TITLE
Failed Agreement/ First response Status Failed Issue

### ISSUE THREAD

**Issue by precihole** [frappe/helpdesk#1659]
In help desk first response column shoiwing "failed", please fix this.
![Screenshot from 2023-12-21 11-00-21](https://github.com/frappe/helpdesk/assets/111174201/40ecd839-cb15-4100-8df6-7051e23a8ae3)

**Comment by michellealva** [comment]
Could you elaborate on the issue?

It is probably showing failed because the agent did not give the first response within the SLA

**Comment by michellealva** [comment]
> if the agent fails to provide the first response within the SLA, it should be marked as a late response. 

In this case it will be marked failed.

> However, the issue is that the response is not being sent,
How though? Email not getting sent from email queue?

cc. @sumitbhanushali

**Comment by RitvikSardana** [comment]
Closing the issue due to inactivity, reopen if the issue still persists
