### ISSUE TITLE
Not able to resolve the issue on HelpDesk.

### ISSUE THREAD

**Issue by precihole** [frappe/helpdesk#1661]
we are not able to resolve the issue when click on resolve option.
![helpdesk issue](https://github.com/frappe/helpdesk/assets/111174201/07c585f5-c2ae-42f2-9abd-3df0d76cc50c)
on helpdesk in erpnext.

**Comment by shadrak98** [comment]
Do you see any error in the console or network tab of the browser?
Please share some more details.

**Comment by sumitbhanushali** [comment]
@precihole are you still facing this issue? Customer field fetches from HD Customer doctype.

Also, update the app and let me know if issue persists

**Comment by RitvikSardana** [comment]
Closing the issue due to inactivity, reopen if the issue still persists
