### ISSUE TITLE
Displaying Custom Fields on Customer Portal Help Desk i

### ISSUE THREAD

**Issue by shubhampreciholesports** [frappe/helpdesk#1662]
I have added a custom field to the HD Ticket (Help Desk Ticket) in my system, and I would like this field to be visible on the Customer Portal, specifically in the Help Desk section. However, the field is not currently displaying on the portal. How can I ensure that this custom field appears on the Customer Portal's Help Desk interface?

**Comment by kittiu** [comment]
You should add that field in HD Ticket Template also, for it to appear. For example, in my case, I added new field "custom_reference" in HD Ticket DocType

![image](https://github.com/frappe/helpdesk/assets/1973598/a17fd125-f4fc-4769-b394-ade9a31edd26)

**Comment by PedroJACorreia** [comment]
Ia there a way to choose a specific Template when opening a new Ticket? Such as when opening a new Ticket, selecting a Ticket Type before the rest of the form, which then loads the custom fields of the respective Ticket Template?

**Comment by RitvikSardana** [comment]
works with HD Ticket Template

**Comment by PedroJACorreia** [comment]
> > Ia there a way to choose a specific Template when opening a new Ticket? Such as when opening a new Ticket, selecting a Ticket Type before the rest of the form, which then loads the custom fields of the respective Ticket Template?
> 
> Is anyone have any solution for this?

I've had to alter and develop the code to align with our needs. I believe the newer version of Helpdesk has more funcionality towards this specific objective, but not quite what we needed, so we're still using the older version.
