### ISSUE TITLE
Error Message Visibility Duration in ERPNext Insight

### ISSUE THREAD

**Issue by shubhampreciholesports** [frappe/helpdesk#1666]
When I execute the SQL script in ERPNext Insight and encounter a SQL error, the error message is displayed for only 3 seconds before disappearing. I would like the error message to remain visible until I manually close it by clicking the cross button.
![ss](https://github.com/frappe/helpdesk/assets/154511820/f1f1c66a-5770-45bb-8f62-8066e1546ff8)

**Comment by mohsinalimat** [comment]
@shubhampreciholesports I think, You posted in wrong repo.

**Comment by shubhampreciholesports** [comment]
ok sorry
