### ISSUE TITLE
Silent failures from frappe.throw

### ISSUE THREAD

**Issue by ankush** [frappe/helpdesk#1668]
I tried to delete my comment which resulted in link validation failure, this error should at least be shown to end user as toast. 

![image](https://github.com/frappe/helpdesk/assets/9079960/7e737fc3-ea30-4515-8490-6361c5e4671f)

**Comment by ankush** [comment]
https://github.com/frappe/frappe-ui/commit/578647ba33f7f93f4087d7ab12a180d647391841

**Comment by netchampfaris** [comment]
https://github.com/frappe/helpdesk/commit/318a7dbc5e3dcb2e32aa3b266cb2ae681eaaeddd
