### ISSUE TITLE
Missing Tickets

### ISSUE THREAD

**Issue by JoSoG89** [frappe/helpdesk#1674]
I get a notification when a ticker is created, then when try to open i cant reach any ticket.

![image](https://github.com/frappe/helpdesk/assets/106213922/0ffaf489-1ae1-492b-8e28-9b7e3841d2e0)

![image](https://github.com/frappe/helpdesk/assets/106213922/420f3f95-13dd-40f4-b5c8-4665541b5f2d)

o dont get any error related to the ticket but i cant found.

**Comment by RitvikSardana** [comment]
Part of old helpdesk, hence closing
