### ISSUE TITLE
Socket Connection Error xhr poll error

### ISSUE THREAD

**Issue by mohsinalimat** [frappe/helpdesk#1677]
When create ticket below error comes.

Socket Connection Error xhr poll error

![Screenshot 2024-01-10 at 11 26 48 AM](https://github.com/frappe/helpdesk/assets/973676/b4384387-efbc-4b79-a721-6b5f02e1e725)

site is on port based(123.123.123.123:80).

Facing issue on version-15

https://discuss.frappe.io/t/socket-connection-error-xhr-poll-error/115652

**Comment by mohsinalimat** [comment]
Still no.

**Comment by RitvikSardana** [comment]
should be fixed now, re-open if the issue still persists
