### ISSUE TITLE
Knowledge Base - Not able to add new articles 

### ISSUE THREAD

**Issue by jahnaviraj** [frappe/helpdesk#1687]
Coming on a new frappe and helpdesk instance. 
![Screenshot from 2024-02-02 11-20-44](https://github.com/frappe/helpdesk/assets/95645706/4334bd5f-b5ae-43cf-bdb7-cffd4107b00d)
Clicking on add new throws out error 

Trying to edit it throws out error in console 
![Screenshot from 2024-02-02 11-21-09](https://github.com/frappe/helpdesk/assets/95645706/715ba4f9-813a-43ee-8906-0c9d8f99d6a8)

**Comment by zuron7** [comment]
I do think it would make much more sense for the knowledge base to be just a Wiki Space of Frappe Wiki considering that the project has been made quite well.

**Comment by jahnaviraj** [comment]
Hi @sumitbhanushali, 
Are there any updates on when this feature will be fixed/completed?
