### ISSUE TITLE
Socket connection error

### ISSUE THREAD

**Issue by maxwell-feng** [frappe/helpdesk#1689]
Socket Connection Error
xhr poll error
<img width="199" alt="01" src="https://github.com/frappe/helpdesk/assets/149435110/e9eda160-f004-4772-b9d5-2e04c986a7a3">

**Comment by mrleeT91** [comment]
same error, check something call from socket.ts and is not call socket client ?

**Comment by sumitbhanushali** [comment]
looks like you are not using `bench start` to start your server. You might be using `bench serve`.

`bench start` also starts up socket server on port 9000

**Comment by RitvikSardana** [comment]
Closing the issue due to inactivity, reopen if the issue still persists
