### ISSUE TITLE
 Add support for retrieving the ticket type when creating a new ticket

### ISSUE THREAD

**Issue by zeel-codder** [frappe/helpdesk#1698]
Currently, System only ask for the `Subject` and `Description` when creating a new ticket. After the ticket is created, we can update the `Ticket Type`. 
We can give users the option to select the `Ticket Type` while they are creating the new ticket as well.

**Comment by KanchanChauhan** [comment]
- This will help in filtering the tickets
- Assignment Rules will be more efficient

<img width="783" alt="Screenshot 2024-02-19 at 5 30 12 PM" src="https://github.com/frappe/helpdesk/assets/16913064/6081d2e8-d10a-474c-a1ef-1eb8f298e23c">

**Comment by sumitbhanushali** [comment]
@KanchanChauhan yes the feature makes sense

**Comment by KanchanChauhan** [comment]
@sumitbhanushali As suggested we have created a PR for this https://github.com/frappe/helpdesk/pull/1700

**Comment by sumitbhanushali** [comment]
merged https://github.com/frappe/helpdesk/pull/1700
