### ISSUE TITLE
Direct comments on HD ticket documents are not reflected on the HD portal.

### ISSUE THREAD

**Issue by precihole** [frappe/helpdesk#1708]
If we comment on the HD ticket document. lt does not reflect on the Helpdesk Portal. As a result, people will remain unaware of what is going on with the situation.

![image](https://github.com/frappe/helpdesk/assets/111174201/2895ffaf-4ba1-4905-8c63-d2824f1f8df9)
![image](https://github.com/frappe/helpdesk/assets/111174201/1f1956fb-7906-4837-8f52-9d92928ebca2)

**Comment by skjbulcher** [comment]
Its true the other way around as well - comments made in HD aren't visible on the HD Ticket document.

**Comment by RitvikSardana** [comment]
because comments are saved in "HD Ticket Comment" DocType
