### ISSUE TITLE
 Inconsistent Resolution Status Message Between Agent Dashboard and Customer Portal

### ISSUE THREAD

**Issue by skibanga** [frappe/helpdesk#1722]
There seems to be a discrepancy in how the Resolution status is displayed between the Agent dashboard and the Customer portal. Specifically, when an operation is met, the Agent dashboard incorrectly displays the status as "failed," whereas the Customer portal correctly shows it as "fulfilled."

![2024-03-14_18-24](https://github.com/frappe/helpdesk/assets/130065778/afedfb5f-e456-4c4a-942d-de70ac657bc9)
![2024-03-14_18-25](https://github.com/frappe/helpdesk/assets/130065778/a3cb8e9b-9fca-4fb4-a155-997e14bb922b)

**Comment by sumitbhanushali** [comment]
@skibanga can you share timestamps of both items? that will help replicate the issue

**Comment by RitvikSardana** [comment]
should be fixed via https://github.com/frappe/helpdesk/pull/1936

**Comment by skibanga** [comment]
Thanks @RitvikSardana
