### ISSUE TITLE
Cannot read properties of undefined (reading 'filter')

### ISSUE THREAD

**Issue by creamdory** [frappe/helpdesk#1725]
Error when creating Ticket

<img width="1441" alt="Ticket error" src="https://github.com/frappe/helpdesk/assets/21003054/e2ab6e88-00db-427f-b7cd-1f790a8680c9">

Versions:
erpnext 15.17.1
frappe 15.17.3
helpdesk 0.10.0
hrms 16.0.0-dev
payments 0.0.1

**Comment by sumitbhanushali** [comment]
fixed in https://github.com/frappe/helpdesk/pull/1726
