### ISSUE TITLE
UX Feedback: Club past conversations

### ISSUE THREAD

**Issue by NehaSan16** [frappe/helpdesk#1734]
Similar to Gmail thread, we could club the older conversations and show a limited preview. This will save time scrolling over past threads and improve agent productivity. 

<img width="1037" alt="Screenshot 2024-03-27 at 8 53 03 AM" src="https://github.com/frappe/helpdesk/assets/139349833/e019d3f6-3706-46db-a74d-3afe94ceb6b8">

**Comment by NehaSan16** [comment]
I noticed an old screenshot, which looks cleaner

<img width="815" alt="Screenshot 2024-03-27 at 9 03 37 AM" src="https://github.com/frappe/helpdesk/assets/139349833/b23ce0f2-b6f6-436e-91c2-ad6721a80111">

**Comment by RitvikSardana** [comment]
This was resolved in the new design for email and comments
