### ISSUE TITLE
Cannot Create Customers

### ISSUE THREAD

**Issue by salieg72** [frappe/helpdesk#1760]
Hi there, hope that someone may be able to assist.
Installed frappe bench on a clean Ubuntu 22.04 machine (VPS)

When I try to create a customer the screen goes blank and then goes back to the customer screen.

## Below is the version of HelpDesk and the screenshots of what I see. 
![image](https://github.com/frappe/helpdesk/assets/54362957/30e4e06a-68c9-4325-b30f-1567ecc0d1d9)

 ## Version of HelpDesk  
![image](https://github.com/frappe/helpdesk/assets/54362957/a259ff30-bed7-45a1-9920-daf92d3e0c5b)

## Where I add the Customer information
![image](https://github.com/frappe/helpdesk/assets/54362957/461c11f9-e8af-49a3-bfe5-9f4c1fa5d83c)

## It goes blank and then I am back at the Customer screen with no Customer.
![image](https://github.com/frappe/helpdesk/assets/54362957/a0d13004-773e-4534-9eb3-e1181a6f48ce)

**I have tried to:**

1. Re-install
2. Looked for any issues with the permissions and cannot see anything obvious.

Appreciate your time and feedback.

Thanks

**Comment by sumitbhanushali** [comment]
@salieg72 can you post screenshot of logs? you can find it in developer tools of chrome

**Comment by salieg72** [comment]
Hi there Sumit

My apologies for the delayed response.
I was using Firefox on Win11 (64-bit)

I tried re-installing the site and I had exactly the same issue.
I then had a look at the ***/sites/{site-name}/logs/***   - not sure what to look for.

Then, I switched to ***Google Chrome*** as you suggested to view the logs.
Enabled developer tools and logged into the Helpdesk site.

- I was able to add a customer with no error. 
- Then I logged back into the Helpdesk with Firefox and the same issue : I could not create a customer.

***Conclusion***
After installing Helpdesk, it ***works with***:
- Google Chrome
- Opera Browser

It did ***not work*** with : 
- Firefox
- Waterfox

I have included screenshots of the exact version that did not work. see below.
![image](https://github.com/frappe/helpdesk/assets/54362957/dec16d49-d31f-4ad8-883f-6ca4ce686480)
![image](https://github.com/frappe/helpdesk/assets/54362957/27b5bbe4-2458-4aa2-8131-507a3328a80d)

**Comment by RitvikSardana** [comment]
Hey @salieg72 , I think the issue is solved can you confirm once?

**Comment by RitvikSardana** [comment]
This issue is fixed
