### ISSUE TITLE
Email Configuration - Different incoming/ outgoing emails for different users

### ISSUE THREAD

**Issue by SukunaCodes** [frappe/helpdesk#1764]
Is it possible to have user specific email setups - incoming and outgoing ones?

For example if I have two users in the system ABC and XYZ. If ABC accesses the system - can the outgoing and incoming mails will be specific to ABC’s mail ID. If I have forwarded emails to Communications form - then will ABC be able to see only emails sent to him in Communications list? Similarly of XYZ?

Kindly help.

**Comment by RitvikSardana** [comment]
Yes it is possible, you can go to settings and configure email account accordingly.
