### ISSUE TITLE
Fresh Install - Cant Submit ticket hd_ticket.api.new Does not Exist

### ISSUE THREAD

**Issue by Henry-Do-Su** [frappe/helpdesk#1773]
Hi, fresh install tested on Frappe v15 with Helpdesk.

![image](https://github.com/frappe/helpdesk/assets/36699432/0fd8ee2a-6cab-4f2e-9a38-6c23405ca7fc)

Tried both on Docker deployment and fresh EC2 Ubuntu 23 and 24 server.

![image](https://github.com/frappe/helpdesk/assets/36699432/c1740618-4b85-47a8-8b33-2017bdd3d5bc)

This was also tested on a docker with a FQDN and SSL cert on HTTPS connection.
Also ran migrate on installation of app

**Comment by carbonitesolutions** [comment]
still getting this error too. have you had any workaround?

**Comment by sumitbhanushali** [comment]
@Henry-Do-Su @carbonitesolutions 
This PR  https://github.com/frappe/helpdesk/pull/1776 probably fixes it, can you check?

**Comment by RitvikSardana** [comment]
Closing the issue due to inactivity, reopen if the issue still persists

**Comment by aliadoinf** [comment]
And what's the solution to this error? It's happening to me right now.
