### ISSUE TITLE
INTERNAL SERVER ERROR when creating new ticket 

### ISSUE THREAD

**Issue by carbonitesolutions** [frappe/helpdesk#1775]
when creating a new ticket at the admin and customer portal when you click on submit then there is an internal server error. 
![Screenshot from 2024-05-12 12-13-45](https://github.com/frappe/helpdesk/assets/110477288/59122e87-18f1-41f0-99bc-c1ba93f6da24)

**Comment by carbonitesolutions** [comment]
this is currently happening both on frappe cloud and local installation

**Comment by aliadoinf** [comment]
And what's the solution to this error? It's happening to me right now.
