### ISSUE TITLE
customer is not listing

### ISSUE THREAD

**Issue by NihalRoshanCK** [frappe/helpdesk#1857]
customer is lot listing in sidebar of ticket when we create a ticket from helpdesk  we can't add the customer from the sidebar i tried to fix it  here is the pr https://github.com/frappe/helpdesk/pull/1854

**Comment by RitvikSardana** [comment]
fixed via: https://github.com/frappe/helpdesk/pull/2063/commits/f82fdaa03cd5954cf66c2a15357c23f00a18fd10
