### ISSUE TITLE
[onboarding] Don't ask for email twice.

### ISSUE THREAD

**Issue by rmehta** [frappe/helpdesk#1877]
> In step 1 you ask for First Name, Last Name & Email and in 2nd step system asks again for the same info which is redundant information from user point of view. I do understand and acknowledge the need of you doing it but it's redundant from the user point of view as they already provided the info in step 1. 

> This potentially is a blocker for any serious apps adopting Frappe cloud for distribution of SaaS applications. 

![image](https://github.com/user-attachments/assets/5d50752d-cbe9-4f1d-aac5-29a53c516d52)

**Comment by RitvikSardana** [comment]
this has been fixed via: https://github.com/frappe/press/pull/1986
