### ISSUE TITLE
Unable to add member to team from web

### ISSUE THREAD

**Issue by thida-bcn** [frappe/helpdesk#1878]
### Information about bug

![image](https://github.com/user-attachments/assets/f900b63d-365f-460d-8ded-d16b2aecac45)
unable to choose member

### Version

Email Delivery Service: v0.0.1 (HEAD)

Frappe Framework: v16.0.0-dev (HEAD)

Helpdesk: v0.10.0 (HEAD)

### Installation method

FrappeCloud

**Comment by RitvikSardana** [comment]
Please update your site, it has been fixed.
Thanks
