### ISSUE TITLE
Customer signup/registration not working

### ISSUE THREAD

**Issue by michellealva** [frappe/helpdesk#1902]
<img width="1437" alt="image" src="https://github.com/user-attachments/assets/fa105093-0f41-433f-99ab-4b5edee7a938">

<img width="1437" alt="image" src="https://github.com/user-attachments/assets/d074aca2-0615-4d31-961c-9358a636ed2c">

Customer cannot signup at all

**Comment by RitvikSardana** [comment]
fixed via #1906
