### ISSUE TITLE
Customer from Customer Portal not been able to raise the Ticket

### ISSUE THREAD

**Issue by JitendraSAW** [frappe/helpdesk#1912]
### Information about bug

Hello Helpdek Team, I have given the Right through Role Permission Manager to the Email Id having the Customer Role but still he is not able to create the Ticker

![image](https://github.com/user-attachments/assets/bfe7f032-b725-4aa9-8fa8-826d721bd6b5)
![image](https://github.com/user-attachments/assets/dd054739-f68c-456d-bc43-8168f5383995)

how the customer who has been raised as a contact in the ERPNext and whom we have provided a Customer Role should be able to create the Ticket. Kindly address this issue as my Implementation is got struck
![image](https://github.com/user-attachments/assets/fb120355-ceeb-46db-a4bb-094c0346c3f7)

### Version

<img width="431" alt="image" src="https://github.com/user-attachments/assets/92f214bc-d92a-4b8f-8adb-71e78be9e07c">

### Installation method

FrappeCloud

**Comment by RitvikSardana** [comment]
Go to HD Settings => Find 'Prefer Knowledge Base' => Disable the option as shown in the image below.
<img width="1440" alt="Screenshot 2024-08-24 at 1 17 17 PM" src="https://github.com/user-attachments/assets/a042cb9f-fca3-484b-bd08-ac2352b7651a">
