### ISSUE TITLE
User Permission Issue

### ISSUE THREAD

**Issue by Indrakumar14m** [frappe/helpdesk#1916]
User Permissions not working as expected with the helpdesk module 
![Screenshot_10](https://github.com/user-attachments/assets/a5ae23e0-e2cf-4a28-9ab8-b5f88f2a5457)
and at the same time not able to edit the Helpdesk related doctypes.

**Comment by sumitbhanushali** [comment]
You need to be on developer mode to be able to edit doctypes.
Otherwise, use customize form instead

**Comment by Indrakumar14m** [comment]
Hi Mr. Sumit, Thank you for your response. I have enabled the Developer mode and now i am able to customize the doctype. but still the user permissions not getting restricted as expected even after making changes.

**Comment by RitvikSardana** [comment]
Invalid Issue closing
