### ISSUE TITLE
Unable to login to erpnext site from Iframe.

### ISSUE THREAD

**Issue by Indrakumar14m** [frappe/helpdesk#1928]
We have a bench setup of ERPNext version 15 on Ubuntu 22.04 server. 

We converted the http site into https through self signed certificate.

The is issue is that we are unable to login and authenticate ERPNext site from iframe. 

It shows "Not Permitted"
![image_2024_08_16T06_14_33_134Z](https://github.com/user-attachments/assets/33b1596a-114c-4356-80ea-2a3f919ba871)

**Comment by RitvikSardana** [comment]
Not a helpdesk issue, closing it
