### ISSUE TITLE
Better diffrentiation between Comment and Reply

### ISSUE THREAD

**Issue by 18alantom** [frappe/helpdesk#1944]
It's happened to me several times that I'll send a Reply, only to have a response a week later from the other side asking for an update. On checking I realize that I had not sent a Reply, and instead sent a Comment.

I do realize that this kind of stupidity occurs from poor design choices, such as abolishing colors from most of our apps, but there has to be a better differentiator.

The both are almost identical:

![Screenshot 2024-08-27 at 10 03 07](https://github.com/user-attachments/assets/da58daea-3f9a-4646-b2b0-484037f87a8b)

![Screenshot 2024-08-27 at 10 02 51](https://github.com/user-attachments/assets/85bd21ad-0951-4af1-844a-b5f6297968cb)

**Comment by RitvikSardana** [comment]
can put a small banner below the reply & comment section , something like comments are for internal team and reply is for the customer.

**Comment by 18alantom** [comment]
<img width="634" alt="Screenshot 2024-10-29 at 17 36 14" src="https://github.com/user-attachments/assets/de2ea1c4-010c-4d7e-9618-489c29025ca2">

🥲


> can put a small banner below the reply & comment section , something like comments are for internal team and reply is for the customer.

sure, as long as it solves the problem, which is to be known only once it's implemented

**Comment by RitvikSardana** [comment]
<img width="801" alt="image" src="https://github.com/user-attachments/assets/94cc6116-903c-4788-8066-f3e6904859df">

fixed
