### ISSUE TITLE
HD Notifications not working in Helpdesk Portal

### ISSUE THREAD

**Issue by Indrakumar14m** [frappe/helpdesk#1957]
### Information about bug

![Screenshot_1](https://github.com/user-attachments/assets/b8f3a9a3-872d-4f4b-ba00-b6b2abcd3d1c)
I am not able receive or see any notification in helpdesk portal

### Version

Frappe-Version: v15.39.0
Frappe-Helpdesk-Version: v0.10.0

### Installation method

manual install

**Comment by RitvikSardana** [comment]
Whatever tickets are assigned to this particular user, will be shown over here.

The notification feature works:
<img width="575" alt="image" src="https://github.com/user-attachments/assets/a6003b4b-f493-49ee-b20f-f45f33446b55">

**Comment by Indrakumar14m** [comment]
![Screenshot_7](https://github.com/user-attachments/assets/99ed871d-730c-4036-9bad-85fcce5a0260)
th
![Screenshot_8](https://github.com/user-attachments/assets/ea34a976-72b5-4aa2-83a8-82d15ff8b79c)
there are more than 20 tickets assigned to that certain user. but still there is no notifications received
