### ISSUE TITLE
Getting duplicate fields while using HD Custom Template

### ISSUE THREAD

**Issue by Indrakumar14m** [frappe/helpdesk#1964]
### Information about bug

![Screenshot_1](https://github.com/user-attachments/assets/2510e40f-6ca8-4bde-a8ef-90a42b283e11)
Showing duplicate fields after creating a ticket using HD Ticket Template. and also not able to choose the customer and contact from helpdesk portal.

### Version

Frappe-Version: v15.39.0
Frappe-Helpdesk-Version: v0.10.0

### Installation method

manual install

**Comment by RitvikSardana** [comment]
Has been fixed
