### ISSUE TITLE
Not able to see the Ticket ID from Customer Portal

### ISSUE THREAD

**Issue by Indrakumar14m** [frappe/helpdesk#1965]
### Information about bug

![Screenshot_7](https://github.com/user-attachments/assets/81d106c4-6ed5-49cb-9c1c-0c55d85b1c8c)
Not able to see the ticket ID from the customer portal after modification. please add a field to show the ticket id after creating the ticket.

### Version

Frappe-version: v15.39.0
Frappe-Helpdesk-Version: v0.10.0

### Installation method

None

**Comment by RitvikSardana** [comment]
This bug is because of the naming series change, the ticket id is the unique identifier, and if you are changing it, then ticket id would not be available in the portal
