### ISSUE TITLE
Can't select customer

### ISSUE THREAD

**Issue by ajiragroup** [frappe/helpdesk#1969]
### Information about bug

I can't select Customer that I created within Helpdesk.

![image](https://github.com/user-attachments/assets/8df72ef1-9cec-4e6c-8849-6dabf69da892)

### Version

![image](https://github.com/user-attachments/assets/1de9eee2-242c-40ea-b386-dff0a7768191)

### Installation method

manual install

**Comment by srikanth-campx** [comment]
Facing Same Issue

**Comment by ksoniyacs** [comment]
Yes. I am too facing the same issue.

**Comment by RitvikSardana** [comment]
fixed via: https://github.com/frappe/helpdesk/pull/2063/commits/f82fdaa03cd5954cf66c2a15357c23f00a18fd10
