### ISSUE TITLE
Back button to see all my tickets in Customer portal

### ISSUE THREAD

**Issue by ajiragroup** [frappe/helpdesk#1972]
### Is your feature request related to a problem? Please describe.

As a customer when I create a new ticket, this screen is loaded
![image](https://github.com/user-attachments/assets/e3e9b865-b4fd-4882-8219-93c25c4d8ad3)

After submitting it,

![image](https://github.com/user-attachments/assets/51f20835-5afd-413d-a7fd-ec82d2507a85)

The only options I have is to "Close".

I don't have an option to go back. I must use browser back button.

### Describe the solution you'd like

Better add a Back  button that takes me back to "All tickets" window.

![image](https://github.com/user-attachments/assets/d8aae16f-5de9-45e1-8b02-68e776584fac)

**Comment by RitvikSardana** [comment]
Should be fixed via new customer portal
