### ISSUE TITLE
Raise ticket on behalf of customer.

### ISSUE THREAD

**Issue by ajiragroup** [frappe/helpdesk#1973]
### Is your feature request related to a problem? Please describe.

I hope everyone agrees that not all customers can login to portal and create issues/ticket. It might also depend upon the nature of business and nature of customers.

Sometimes, depending on nature of business, customers, they might register an issue via phone call and the agent/CSR might have to register it on behalf of the customer.

### Describe the solution you'd like

While Creating a ticket, there must be an option to select Customer/Contact when ticket is being created by Agent/Or other users.

**Comment by RitvikSardana** [comment]
fixed via: https://github.com/frappe/helpdesk/pull/2063/commits/f82fdaa03cd5954cf66c2a15357c23f00a18fd10

After creating a ticket, you can select the customer for the ticket, and link the customer to the ticket
