### ISSUE TITLE
All emails pulled as ticket.

### ISSUE THREAD

**Issue by ajiragroup** [frappe/helpdesk#1974]
### Information about bug

For testing Helpdesk, I added my real mail address into helpdesk.

After a few hours I noticed, all my emails from the Gmail account were pulled as tickets. 

When we use Helpdesk, we will definitely onboard employees who are already on ERPNext, and will use their real personal email addresses (or company email addresses) in both ERPNExt and on Helpdesk.

If everyone's communication is pulled as ticket, that is going to be a problem.

### Version

![Uploading image.png…]()

### Installation method

manual install

**Comment by srikanth-campx** [comment]
+1

**Comment by RitvikSardana** [comment]
Thing is, initially, the framework syncs 100 emails, and then from there all new emails are synced.

This is not a but it's how the framework works
