### ISSUE TITLE
error when installing helpdesk

### ISSUE THREAD

**Issue by AlexisDali** [frappe/helpdesk#1982]
Hello my friends.
I am trying to install frappe helpdesk on my erpnext, I follow this link:https://github.com/frappe/helpdesk
when i run this command: **bench --site helpdesk.test install-app helpdesk** I get this error
_An error occurred while installing helpdesk: (1045, "Access denied for user '_011f7aeb9ad26be4'@'localhost' (using password: YES)")
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 445, in install_app
    _install_app(app, verbose=context.verbose, force=force)
      context = {'sites': ['helpdesk.test'], 'force': False, 'verbose': False, 'profile': False}
      apps = ('helpdesk',)
      force = False
      _install_app = <function install_app at 0x7adf2ca6ad40>
      filelock = <function filelock at 0x7adf2ca68540>
      exit_code = 0
      site = 'helpdesk.test'
      app = 'helpdesk'
      err = OperationalError(1045, "Access denied for user '_011f7aeb9ad26be4'@'localhost' (using password: YES)")
  File "apps/frappe/frappe/installer.py", line 265, in install_app
    frappe.clear_cache()
      name = 'helpdesk'
      verbose = False
      set_as_patched = True
      force = False
      sync_jobs = <function sync_jobs at 0x7adf2b9d7b00>
      sync_for = <function sync_for at 0x7adf2b9e4860>
      sync_customizations = <function sync_customizations at 0x7adf2ca34f40>
      sync_fixtures = <function sync_fixtures at 0x7adf2b9e4b80>
  File "apps/frappe/frappe/__init__.py", line 1017, in clear_cache
    for key in frappe.get_hooks("persistent_cache_keys"):
      user = None
......etc_
bench version is: 5.22.9
my node version is:v18.20.4
erpnext 15.35.1
frappe 15.40.6
hrms 16.0.0-dev
payments 0.0.1
raven 1.7.0
anyone encounter such issue before..?

**Comment by RitvikSardana** [comment]
This looks like, the password which you are putting for the sql is wrong.
You need to put correct SQL root password

**Comment by EasternIndustries-IT** [comment]
It also errors in apps.json
apps.json 
`
  {
    "url": "https://github.com/frappe/helpdesk.git",
    "branch": "v0.10.0"
  }`

The error returned
`548.6 Getting helpdesk
548.6 $ git clone https://github.com/frappe/helpdesk.git --branch v0.10.0 --depth 1 --origin upstream
548.6 subprocess.CalledProcessError: Command 'git clone https://github.com/frappe/helpdesk.git --branch v0.10.0 --depth 1 --origin upstream' returned non-zero exit status 128.
548.6
548.6 The above exception was the direct cause of the following exception:
548.6
548.6 Traceback (most recent call last):
548.6   File "/usr/local/lib/python3.11/site-packages/bench/commands/make.py", line 75, in init
548.6     init(
548.6   File "/usr/local/lib/python3.11/site-packages/bench/utils/render.py", line 105, in wrapper_fn
548.6     return fn(*args, **kwargs)
548.6            ^^^^^^^^^^^^^^^^^^^
548.6   File "/usr/local/lib/python3.11/site-packages/bench/utils/system.py", line 98, in init
548.6     install_apps_from_path(apps_path, bench_path=path)
548.6   File "/usr/local/lib/python3.11/site-packages/bench/app.py", line 1030, in install_apps_from_path
548.6     get_app(
548.6   File "/usr/local/lib/python3.11/site-packages/bench/app.py", line 770, in get_app
548.6     app.get()
548.6   File "/usr/local/lib/python3.11/site-packages/bench/utils/render.py", line 126, in wrapper_fn
548.6     return fn(*args, **kwargs)
548.6            ^^^^^^^^^^^^^^^^^^^
548.6   File "/usr/local/lib/python3.11/site-packages/bench/app.py", line 203, in get
548.6     self.bench.run(
548.6   File "/usr/local/lib/python3.11/site-packages/bench/bench.py", line 48, in run
548.6     return exec_cmd(cmd, cwd=cwd or self.cwd, _raise=_raise)
548.6            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
548.6   File "/usr/local/lib/python3.11/site-packages/bench/utils/__init__.py", line 178, in exec_cmd
548.6     raise CommandFailedError(cmd) from subprocess.CalledProcessError(return_code, cmd)
548.6 bench.exceptions.CommandFailedError: git clone https://github.com/frappe/helpdesk.git --branch v0.10.0 --depth 1 --origin upstream
548.6
548.6 ERROR: There was a problem while creating /home/frappe/frappe-bench
548.6 Do you want to rollback these changes? [y/N]:`

**Comment by RitvikSardana** [comment]
Unrelated to Frappe Helpdesk. Closing the issue.

Seems like Frappe Docker issue
