### ISSUE TITLE
Insufficient Permission for HD Service Level Agreement

### ISSUE THREAD

**Issue by clayrisser** [frappe/helpdesk#2002]
### Information about bug

I created a form for Guests to create support tickets. I am unable to get it to work.

Below is the code I created for it, but I an error.

```
        new_ticket = frappe.get_doc({
            "doctype": "HD Ticket",
            "subject": "Website Support Request",
            "description": message,
            "priority": "Urgent",
            "ticket_type": "Question",
            "status": "Open"
        })
        new_ticket.insert(ignore_permissions=True)
        frappe.db.commit()
```

### Version

Frappe Builder: v1.11.5

Education: v15.3.2

ERPNext: v15.34.0

Frappe Framework: v15.8.1

Helpdesk: v0.10.0

Frappe HR: v15.28.0

Payments: v0.0.1

Scrum: v0.0.1

### Installation method

Kubernetes

### Relevant log output / Stack trace / Full Error Message.

```shell
'["Traceback (most recent call last):\\n File \\"apps/frappe/frappe/app.py\\", line 114, in application\\n response = frappe.api.handle(request)\\n ^^^^^^^^^^^^^^^^^^^^^^^^^^\\n File \\"apps/frappe/frappe/api/__init__.py\\", line 49, in handle\\n data = endpoint(**arguments)\\n ^^^^^^^^^^^^^^^^^^^^^\\n File \\"apps/frappe/frappe/api/v1.py\\", line 36, in handle_rpc_call\\n return frappe.handler.handle()\\n ^^^^^^^^^^^^^^^^^^^^^^^\\n File \\"apps/frappe/frappe/h…esk/helpdesk/utils.py\\", line 23, in check_permissions\\n frappe.throw(f\\"Insufficient Permission for {doctype}\\", frappe.PermissionError)\\n File \\"apps/frappe/frappe/__init__.py\\", line 652, in throw\\n msgprint(\\n File \\"apps/frappe/frappe/__init__.py\\", line 617, in msgprint\\n _raise_exception()\\n File \\"apps/frappe/frappe/__init__.py\\", line 568, in _raise_exception\\n raise exc\\nfrappe.exceptions.PermissionError: Insufficient Permission for HD Service Level Agreement\\n"]'
```

**Comment by clayrisser** [comment]
I tried creating a web form and I get the same error.

<img width="964" alt="Screenshot 2024-09-26 at 4 37 34 PM" src="https://github.com/user-attachments/assets/ffd31cda-0ee2-419d-a23e-f9ab988e3d52">

**Comment by clayrisser** [comment]
I disabled Track SLA from the settings and I still get the error.

<img width="383" alt="Screenshot 2024-09-26 at 4 38 50 PM" src="https://github.com/user-attachments/assets/c7cbd50d-2679-4014-bed2-50280839b92a">

**Comment by clayrisser** [comment]
@RitvikSardana do you know what causes this issue?

**Comment by clayrisser** [comment]
@RitvikSardana any updates on this?

**Comment by RitvikSardana** [comment]
already fixed

**Comment by clayrisser** [comment]
Works great!
