### ISSUE TITLE
Add different statuses according to our standard.

### ISSUE THREAD

**Issue by avanishjha** [frappe/helpdesk#2006]
### Information about bug

I wanna create custom ticket statuses like Open, Accepted, Assigned, Resolved, Closed instead of default ones. Is there any way to do so 

### Version

Frappe 15.x.x-develop 
Frappe Helpdesk- 0.10.0

### Installation method

manual install

**Comment by RitvikSardana** [comment]
nope, the helpdesk is build with keeping in mind that there are only 4 status


Open 
Replied
Resolved
Closed
