### ISSUE TITLE
No Scrollbar ability on screens with small height

### ISSUE THREAD

**Issue by ascorbic-acid** [frappe/helpdesk#2010]
### Information about bug

as presented  in this video on "create ticket" page some people with specific screen heights cannot see the bottom "discard" "send" buttons etc:

[Screencast from 2024-10-06 12-01-19.webm](https://github.com/user-attachments/assets/fcaa122b-5939-4bda-baad-d54b68813bc8)

### Version

erpnext 15.36.1
frappe 15.41.0
helpdesk (6cdea66 develop)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
.
```

**Comment by dufani1** [comment]
we face this issue too

**Comment by RitvikSardana** [comment]
Fixed, we have a new customer portal now
