### ISSUE TITLE
User permission not working

### ISSUE THREAD

**Issue by aidemkin** [frappe/helpdesk#2025]
### Information about bug

In the current version of the customer portal, business users can see all created tickets, regardless of the company they belong to. This is unacceptable because users represent different companies, and such logic violates privacy policies, creating business risks, including potential fines for data breaches.

The functionality of the portal is only suitable in cases where there is only one client or the company is non-commercial. To address this issue, we kindly ask you to add a feature that allows ticket visibility to be segmented by company or author. Ideally, this option should be configurable based on the specific business needs of each company.

### Version

Frappe version - 15.45.1
Helpdesk version - 1.0.0

### Installation method

manual install

**Comment by RitvikSardana** [comment]
Nope, this is not the case, a user can see the tickets which they have created.


If 2 contacts represent the same customer (company). Then only both users tickets are visible to each other.

**Comment by aidemkin** [comment]
@RitvikSardana 

I am probably not connecting the user and the company correctly. Please clarify how to correctly perform this action.
