### ISSUE TITLE
pymysql.err.OperationalError: (4089, "'db.hd_preset_filter_item_id_seq' is not a SEQUENCE")

### ISSUE THREAD

**Issue by fzhan** [frappe/helpdesk#2027]
### Information about bug

bench --site=site install-app helpdesk report logs
pymysql.err.OperationalError: (4089, "'db.hd_preset_filter_item_id_seq' is not a SEQUENCE")

### Version

erpnext 15.38.4
frappe 15.44.2
helpdesk 1.0.0
hrms 15.32.2
insights 2.2.6
lms 2.7.0
payments 0.0.1

### Installation method

manual install

**Comment by RitvikSardana** [comment]
what is the issue, how did you get it?

what are the steps to replicate?
What page you got this issue on?

**Comment by fzhan** [comment]
@RitvikSardana , problem solved, it was a db recovery gone wrong, and a fresh installation with migration fixed it.
