### ISSUE TITLE
Status selector options' icons are all gray

### ISSUE THREAD

**Issue by 18alantom** [frappe/helpdesk#2028]
### Information about bug

![Screenshot 2024-10-31 at 10 26 16](https://github.com/user-attachments/assets/79957380-628e-45d2-9583-29aa85ab1a05)

### Version

[`develop, afda3ff`](https://github.com/frappe/helpdesk/commit/afda3ff3a42d84af7c6f19d0c100b273e0cc1271)

### Installation method

FrappeCloud

**Comment by RitvikSardana** [comment]
Was a frappe-ui issue, fixed it
