### ISSUE TITLE
Remove /  Deactivate Agent

### ISSUE THREAD

**Issue by ashishsaretia** [frappe/helpdesk#2040]
### Is your feature request related to a problem? Please describe.

How can we remove agents once added to the system, currently there is none.
Attaching screenshot for reference.
![image](https://github.com/user-attachments/assets/ff5ca2a4-f1aa-490f-a070-05ee2681606d)

### Describe the solution you'd like

Any option to remove a particular agent on the Agents screen

**Comment by ashishsaretia** [comment]
Also, the tickets are assigned to me with email notifications but here it shows "Inactive"

**Comment by RitvikSardana** [comment]
Update your helpdesk, this issue has been fixed

**Comment by ashishsaretia** [comment]
@RitvikSardana no update is available over Frappe Cloud. Can you please get this checked and reconfirm on the same? Thanks
