### ISSUE TITLE
Empty communication created when creating ticket via email

### ISSUE THREAD

**Issue by joshuarestivo** [frappe/helpdesk#2041]
### Information about bug

When a new ticket is created via email, a second communication is automatically added to the ticket. It's always from Administrator and its content is 'null'. [This code](https://github.com/frappe/helpdesk/blob/d810e34dac0f5cb0c0b62c56195eec106780cfbc/helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py#L194C1-L197C1) is what causes it. What is this supposed to be doing?

### Version

Frappe - v15.47.1
Helpdesk - d810e34dac0f5cb0c0b62c56195eec106780cfbc

### Installation method

None

**Comment by RitvikSardana** [comment]
Fixed
