### ISSUE TITLE
Tickets should not be closed without a resolution comment; make the resolution command as mandatory

### ISSUE THREAD

**Issue by varshapriyas** [frappe/helpdesk#2054]
### Is your feature request related to a problem? Please describe.

"Once the issue is resolved, the agent must provide a resolution comment in the ticket. The 'Resolution Comment' field should be made mandatory."

**Comment by RitvikSardana** [comment]
This is a customisation, and can be done, by adding new custom fields, like
reponse failure reason or resolution failure reason 
for which you can write server scripts to make it mandatory
