### ISSUE TITLE
How customer can login

### ISSUE THREAD

**Issue by RajbirSehrawat** [frappe/helpdesk#2064]
Can you suggest on this

1. How can a customer login to see his tickets closed or opened? (How to  create customer username and password)
2. How customers are notified by email. once a replied customer ticket.

**Comment by RitvikSardana** [comment]
1. From your website settings, you can enable signups, then users can sign up for your portal. Hence they can submit new tickets or reply to older ones.
2. When an agent replies on a ticket the ticket status changes to open, which send an email to the customer.
