### ISSUE TITLE
Auto-reply on ticket creation

### ISSUE THREAD

**Issue by casesolved-co-uk** [frappe/helpdesk#2086]
### Is your feature request related to a problem? Please describe.

No auto replies

### Describe the solution you'd like

If a ticket is opened by email, ability to configure and send an auto-reply with details of the SLA. Only on initial ticket creation.

### Describe the alternatives you've considered

It is possible to configure a global auto-reply on the email account, but this will be sent for every email.

**Comment by Cellhitch** [comment]
Hi Richard, 
I am using a self-hosted Frappe Helpdesk app. I have the same problem and have created a notification to get it done. Please see my screenshot. The notification is triggered when a new ticket is opened.
![image](https://github.com/user-attachments/assets/8233d025-5796-498e-be9e-737338fba3fa)

Regards,
Hitch

**Comment by casesolved-co-uk** [comment]
Yes good idea, I created one to notify me of new tickets but didn't think about customers
