### ISSUE TITLE
Contact, Customer and Email Account not being set on Tickets

### ISSUE THREAD

**Issue by casesolved-co-uk** [frappe/helpdesk#2095]
### Information about bug

Contact, Customer and Email Account fields are being left blank on Tickets created from incoming emails

### Version

Frappe Framework: v15.43.0 (version-15)
Helpdesk: v1.2.0 (main)

### Installation method

None

**Comment by RitvikSardana** [comment]
Yeah obviously it will remain blank
From email we can only get subject and body.

**Comment by wmburke** [comment]
Can someone please expand on this for me? From email, you can also get the email address, which if tied to an existing customer will give you both contact and customer name. If the email is not already in the system, then it may also be possible to pull a name off the email. It's also possible that the email address will be from a domain that would connect the contact to an existing customer.

Does any of this happen currently?

**Comment by RitvikSardana** [comment]
makes sense @wmburke , I will add this functionality, can you create this as a separate issue please?

**Comment by wmburke** [comment]
Done, @RitvikSardana - Here it is: https://github.com/frappe/helpdesk/issues/2165.

Thanks.
