### ISSUE TITLE
Auto Update Status behaviour

### ISSUE THREAD

**Issue by casesolved-co-uk** [frappe/helpdesk#2110]
### Information about bug

Auto update status sets the Status of a Ticket to Replied on sending any Communication (Email). This could be sent by the agent or an auto-reply sent from frappe Notifications.
This is incorrect behaviour.

What should happen:

- If the agent sends an email from the ticket interface in the Helpdesk the Ticket should always be set to Replied;
- If any other email is sent, i.e. from a Notification, the status should not be modified.

Please remove the option in settings.

https://github.com/frappe/helpdesk/blob/0db7083de8d0a97cee90e8b9e81c1db466786918/helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py#L754-L755

### Version

v1.2.0

### Installation method

None

**Comment by RitvikSardana** [comment]
You can disable the settings as of now.
Will be refactoring this in some time

**Comment by casesolved-co-uk** [comment]
This obviously isn't completed then.
