### ISSUE TITLE
loading page animation

### ISSUE THREAD

**Issue by harshit-30** [frappe/helpdesk#414]
we need better screen/idea to showcase loading instead of this: 

![CleanShot 2022-05-17 at 16 56 51](https://user-images.githubusercontent.com/46772424/168802081-63e4d0c8-3f18-4df1-a937-79589a2f8fe5.gif)

**Comment by harshit-30** [comment]
the animation part is still missing.

**Comment by nish7x** [comment]
@harshit-30 Animation below. 


https://user-images.githubusercontent.com/8917840/187421111-465aad9b-893e-47dc-b3d8-86cdc174b883.mov
