### ISSUE TITLE
feat: update status while sending 

### ISSUE THREAD

**Issue by harshit-30** [frappe/helpdesk#462]
Add an ability to mark it as Replied, Resolved, or Closed while sending a message. 
the options should be: 
- Send
- Send and set as Replied 
- Send and set as Resolved 
- Send and set as Closed

`Send should be the default option`

it should look something like this: 
<img width="437" alt="image" src="https://user-images.githubusercontent.com/46772424/170047220-e2ccc838-e3ea-4bd5-875c-50744312adf6.png">

**Comment by fadilsid** [comment]
resolved in #947 [6ffa2a9](https://github.com/frappe/helpdesk/pull/947/commits/6ffa2a9e6962b30618aa791e3727061f45bd5f5a)


![Image](https://user-images.githubusercontent.com/73826691/212292165-ee57fce7-2188-4470-b2f3-927e5f646a50.png)
