### ISSUE TITLE
empty list view design

### ISSUE THREAD

**Issue by harshit-30** [frappe/helpdesk#518]
@nish7x we don't have a design when a list view is empty. 

We can add some text like: 

- Sit back and relax, until the next ticket comes in. 
- Take a break and stretch a little, until the next ticket arrives. 

I am visualizing something like this without the button: 

![image](https://user-images.githubusercontent.com/46772424/176406765-5d063650-f89a-4e5c-a772-061a4c006b2c.png)

It has a doodle backed by some text.

**Comment by harshit-30** [comment]
@nish7x anything which comes to your mind?

**Comment by nish7x** [comment]
@harshit-30 


![Image](https://user-images.githubusercontent.com/8917840/183624887-3b97038f-67de-455f-8c32-64bb2f88fbf7.png)


Figma link: https://www.figma.com/file/3sLEVJgMVFFGGKVJ3f7qFS/FrappeDesk?node-id=5007%3A20207
