### ISSUE TITLE
remove old support settings

### ISSUE THREAD

**Issue by harshit-30** [frappe/helpdesk#595]
- [x] rename Support settings to Frappe Desk Settings
- [ ] remove Support Portal code
- [ ] remove latest forum posts section
- [x] remove Greetings code 
- [x] remove search API's code 
- [x] remove setup complete checkbox
- [x] hide initial agent and ticket creation checkbox

**Comment by harshit-30** [comment]
The Support portal thing still exists, any particular reason why? @kamaljohnson 

<img width="1288" alt="image" src="https://user-images.githubusercontent.com/46772424/188401603-a8488d20-feef-4626-9c4f-908f2d7ab475.png">

**Comment by kamaljohnson** [comment]
Closing this as the left of todo item has been converted to an issue
