### ISSUE TITLE
An error occurred while installing frappedesk

### ISSUE THREAD

**Issue by excel-azmin** [frappe/helpdesk#688]
Installing frappedesk...
Updating DocTypes for frappedesk    : [========================================]
An error occurred while installing frappedesk:
execute() got an unexpected keyword argument 'pluck'

![image](https://user-images.githubusercontent.com/92359442/187058220-1900004c-d6b5-4bf5-9422-c6d596bbe00e.png)

**Comment by kamaljohnson** [comment]
@excel-azmin, Which version of frappe are you using?
