### ISSUE TITLE
Adding Support Agent - Email domain Issue

### ISSUE THREAD

**Issue by nanoharsha** [frappe/helpdesk#728]
While adding a support email agent, it is detecting an email id automatically after first full stop, as in support@helpdesk.com, in case the email id is "support@helpdesk.org.in" , it isn't detecting it and hence the support email id can't be added. 
Probably using "," as a delimter to detect email id's would be better way ofdetecting email ids.

**Comment by joshuarestivo** [comment]
Experiencing the same issue here. Without digging further, it looks like frappedesk is trying to validate the email addresses. I don't know if this is frappedesk or frappe, proper. Regardless, an email with a "." in the username or a domain that begins with a number fail to meet the validation criteria even though they're valid.

**Comment by joshuarestivo** [comment]
https://github.com/frappe/desk/pull/816
