### ISSUE TITLE
Error with Logo size in Frappe Desk (ERPNext 14)

### ISSUE THREAD

**Issue by 0xhaval** [frappe/helpdesk#740]
# Hi,

I found a bug in CSS in the Frappe Desk home page (support/ticket)
I change the Logo and is display very big size as follow

![Screenshot 2022-10-02 123143](https://user-images.githubusercontent.com/35600969/193510461-b71324ae-ae57-4f01-b28a-7ebb53fb7538.png)

Thanks,

[Reference](https://discuss.erpnext.com/t/error-with-logo-size-in-frappe-desk-erpnext-14/95445)

**Comment by egarmendia-dac** [comment]
I am having the same issue
