### ISSUE TITLE
Installing and uninstalling frappe/desk breaks ERPNext

### ISSUE THREAD

**Issue by tejpochiraju** [frappe/helpdesk#750]
Filing this issue here as this is a doctype name collision issue and I presume ERPNext takes precedence as the older project?

I was testing this application on an existing bench with ERPNext installed. I uninstalled it because of #749 but then realised that the `Support` module inside ERPNext broke as a result.

The reason was that both apps have a doctype called `Support Search Source` and uninstalling this app deletes the doctype. Recovery requires running `bench --site sitename migrate` again.

**Comment by harshit-30** [comment]
please dont install Frappe Desk alongside ERPNext for now to avoid this issue.
