### ISSUE TITLE
ModuleNotFoundError: No module named 'frappedesk.hooks'

### ISSUE THREAD

**Issue by creative-paramu** [frappe/helpdesk#751]
When I install frappedesk app to my site this error was arising , I was migrate and reinstall site , but this error not solved how to solve this?
![Screenshot from 2022-10-18 10-05-04](https://user-images.githubusercontent.com/101092028/196336718-5284efcd-6395-4419-8ea5-1d27dfd64a7f.png)

**Comment by harshit-30** [comment]
please create a new ticket if you're still facing this issue.
