### ISSUE TITLE
Reset password has either been used before or is invalid

### ISSUE THREAD

**Issue by joshuarestivo** [frappe/helpdesk#769]
When a user follows the link sent to them when being added as an agent, they get the password reset page. Entering a new password and selecting Confirm sometimes (I can't find any consistency yet) results in "Invalid Link - The reset password link has either been used before or is invalid"

**Comment by jahnaviraj** [comment]
The link expires in 20 minutes if using the default settings. Could this be the cause?

**Comment by RitvikSardana** [comment]
correct @jahnaviraj 

do re open the issue if it still persists
