### ISSUE TITLE
[knowledge Base] - article navigation

### ISSUE THREAD

**Issue by federicocalvo** [frappe/helpdesk#771]
### Description:

In the article view, there is a space on the right (probably a col-md-4 or 3).

![Captura de pantalla 2022-11-03 a la(s) 16 01 08](https://user-images.githubusercontent.com/7256766/199812804-286bca50-f377-4cd5-901e-5a4dccbc183f.png)

### Solution:

It would be very interesting to have a function identical to the wiki, to be able to navigate in long articles through h1 h2

![Captura de pantalla 2022-11-03 a la(s) 16 01 50](https://user-images.githubusercontent.com/7256766/199812837-93ca1fa7-d1ec-455f-91b7-ab7ebfbd328e.png)

**Comment by aiswaryals1997** [comment]
> ### Description:
> 
> In the article view, there is a space on the right (probably a col-md-4 or 3).
> 
> ![Captura de pantalla 2022-11-03 a la(s) 16 01 08](https://user-images.githubusercontent.com/7256766/199812804-286bca50-f377-4cd5-901e-5a4dccbc183f.png)
> ### Solution:
> 
> It would be very interesting to have a function identical to the wiki, to be able to navigate in long articles through h1 h2
> 
> ![Captura de pantalla 2022-11-03 a la(s) 16 01 50](https://user-images.githubusercontent.com/7256766/199812837-93ca1fa7-d1ec-455f-91b7-ab7ebfbd328e.png)

Would you kindly explain us how to edit a knowledge base page?

**Comment by kamaljohnson** [comment]
@aiswaryals1997, to edit the knowledge base articles

got to Knowledge Base inside frappedesk agent view, `url: /frappedesk/kb`

<img width="250" alt="image" src="https://user-images.githubusercontent.com/22856401/200260139-6146556a-71fc-4257-ac21-58853b6b97e6.png">

click on the `Knowledge Base` sidebar element

here you can see the webview of the knowledge base, you can click on `Edit` button on the top to create / arrange categories & published articles.

Editing articles
go to article list, by switching to article list from the webview

<img width="307" alt="image" src="https://user-images.githubusercontent.com/22856401/200260617-cf483fe0-4b2b-4f8c-bc71-ff8ff879042b.png">

Here you can see all the articles, both published / drafts

you can click on the articles and edit it and also mark it as published (which will make it visible to the customers)
