### ISSUE TITLE
In customer portal, new chat can be viewed only when we refresh that page. Any solutions?

### ISSUE THREAD

**Issue by aiswaryals1997** [frappe/helpdesk#774]
![image](https://user-images.githubusercontent.com/61047968/200103091-eea296d5-5805-42a0-8d56-5a0bdc9f2979.png)

**Comment by kamaljohnson** [comment]
Are you using the latest version of frappedesk? 

There was a socketio issue in the older version of frappedesk, it was fixed in the newer versions.
please do `bench build`, and check if you are still facing this issue.

**Comment by aiswaryals1997** [comment]
checked but its not working
