### ISSUE TITLE
Design: Too many toggles; default is repeating twice

### ISSUE THREAD

**Issue by mayanknahata007** [frappe/helpdesk#825]
<img width="780" alt="Screenshot 2022-11-21 at 10 34 47 AM" src="https://user-images.githubusercontent.com/88381410/203016727-bb22e2a0-6674-42ed-9aad-c71750609ec5.png">

I get what this means, but it feels like something could be changed to make it look better.

**Comment by RitvikSardana** [comment]
Part of old helpdesk
