### ISSUE TITLE
feat: Dashboard

### ISSUE THREAD

**Issue by harshit-30** [frappe/helpdesk#839]
Add a new sidebar item - Dashboard. 

- [x] The Dashboard will be a default one - currently non-editable.
- [x] It will reflect all the metrics reflected in the image below.
- [x] Filtering as per dates is available. 

![dashboard](https://user-images.githubusercontent.com/46772424/204517105-880f88fc-1070-4bcb-9c7d-f2be6ac4391d.png)

**Comment by fadilsid** [comment]
#878

**Comment by harshit-30** [comment]
@fadilsid please mark the tasks as completed once you have resolved them.
