### ISSUE TITLE
Agent detail Title edit mode not exited

### ISSUE THREAD

**Issue by moroslantia** [frappe/helpdesk#843]
### Reproduce
- Open the detailed view of a agent
- Click the pen icon to edit the name
- Click on the cross to cancel editing

![image](https://user-images.githubusercontent.com/23380283/204845041-7608891f-4c5e-4a71-94d5-abf67c2bdc57.png)

### Expected
- Changes are reset
- Edit mode is closed

### Observed
- changes are reset
- Edit mode stays active

**Comment by RitvikSardana** [comment]
Part of old helpdesk
