### ISSUE TITLE
Email Accounts creation and detail view has issues

### ISSUE THREAD

**Issue by moroslantia** [frappe/helpdesk#844]
### Reproduce
Go to Email Accounts
Click "+ New Email"

### Expected
Enter details and setup a new email account

### Observed
- Not possible to enter all relevant data. 
- No success to add a new email account
- Service selector has no effect
- Service selection is not stored

**Comment by RitvikSardana** [comment]
Must have been solved now, do re open the issue in case if the issue still persists.
