### ISSUE TITLE
Mail new ticket via mail leads to error prone actions

### ISSUE THREAD

**Issue by moroslantia** [frappe/helpdesk#845]
### Reproduce
Sent a new mail to the desk account for tickets

A mail is sent to which user? (Not clear who will receive the notification and why)

### Expected
A mail and link to the ticket to take further actions with new created ticket number in the title

### Observed
Mail with same Subject and content as sent my the issuer received. 
It can't be understood where the mail comes from and that it is a ticket. 
Replying to this mail would not be tracked by the Desk (even not knowing that it is a mail from the Desk App)

**Comment by harshit-30** [comment]
@moroslantia Hello, I need more context on this. By default, the mail is sent to the user assigned to it. The Assignment Rule DocType decides the assignment. A notification is sent to the User with the link to the ticket to open it in the browser.

**Comment by moroslantia** [comment]
Sending following mail to support system (creates and assign the ticket as defined in rules) 

![image](https://user-images.githubusercontent.com/23380283/206689373-ad8e2351-f1eb-4a4d-9185-c4ffbcf24b8a.png)

But the send out mail of the ticket system is:

![image](https://user-images.githubusercontent.com/23380283/206689754-d635da3d-0a64-46ce-a7b7-ac630b4353df.png)

There is no link to the ticket, nor any hint that this mail comes from the desk app.
I miss any detail of the ticket (Ticket number, assignee rule or whatever might make sense)

**Comment by RitvikSardana** [comment]
Is this issue still valid? @moroslantia

**Comment by RitvikSardana** [comment]
Re open if the issue still persists
