### ISSUE TITLE
404 Not Found on /frappedesk/tickets 

### ISSUE THREAD

**Issue by guilfb** [frappe/helpdesk#851]
Hi, 

I am trying to install FrappeDesk on a remote Ubuntu 22.04 server.
I tried to build my custom image with frappedesk extension, using this [very helpful repo](https://github.com/castlecraft/custom_frappe_docker). 
I guess I did it well because I did it for other extensions before ([hrms](https://github.com/frappe/hrms)).

I then used the pwd.yml file as a test docker compose, using my built images instead of frappe images from the docker hub.

I ended up with this interface :  <img width="1345" alt="Capture d’écran 2022-12-01 à 17 58 15" src="https://user-images.githubusercontent.com/35146908/205113486-b7aa6794-ad6f-41d4-bc1f-1b4f571443ef.png">

The thing is that the link behind `Go To Frappe Desk`, which brings me to `/frappedesk/tickets` returns a 404 : 
<img width="1294" alt="Capture d’écran 2022-12-01 à 17 59 15" src="https://user-images.githubusercontent.com/35146908/205113730-9c706a8d-fe0a-40cd-9a49-a5fdc061beca.png">

I don't really understand why I have nothing behind this page.

Another question, which I guess is linked to the first one, is : where can I find this page (screenshot from the frappedesk repo) :

<img width="1258" alt="Capture d’écran 2022-12-01 à 18 01 08" src="https://user-images.githubusercontent.com/35146908/205114134-a48047de-76fd-4547-8447-1db058ce6e6c.png">

Many thanks by advance,

guilfb

**Comment by kamaljohnson** [comment]
@guilfb the link is actually `/frappedesk/tickets` and not `/frappedesk/tickers` was this typo the issue?

**Comment by 0FiRE0** [comment]
Same issue here.
```
Installed Apps
Education: v0.0.1
ERPNext: v14.7.0
Frappe Framework: v14.15.0
FrappeDesk: v0.5.7
Frappe HR: v1.0.0
Frappe Insights: v0.1.0-beta
Payments: v0.0.1
```

**Comment by guilfb** [comment]
@kamaljohnson 
Any updates about this issue ? Or do you know versions of `Frappe Framework`, `ERPNext` and `Frappe Desk` that are working together ?
Many thanks

**Comment by guilfb** [comment]
Hi there, any updates please ? @kamaljohnson @harshit-30
Thanks by advance to anyone with a solution to make frappedesk working with frappe_docker.

**Comment by 0FiRE0** [comment]
Hi there,
Could you please let us know if this issue was resolved or not yet.
We appreciate your support @kamaljohnson @nish7x

**Comment by guilfb** [comment]
> Hi there,
> Could you please let us know if this issue was resolved or not yet.
> We appreciate your support @kamaljohnson @nish7x

Hi there,
Nope I couldn't solve the problem yet, the link is still not working.
I would appreciate some help if possible ! @kamaljohnson @nish7x  @harshit-30

**Comment by ellicodan** [comment]
I'm having the same issue. Any fix for this?
![image](https://user-images.githubusercontent.com/88472078/216168499-4139af6d-9e01-4daa-a1ec-1af5aee4549a.png)
