### ISSUE TITLE
Support Policy UI Clean up

### ISSUE THREAD

**Issue by harshit-30** [frappe/helpdesk#859]
- [x] Clicking on switch buttons doesn't respond immediately and sometimes never. _(under Rules section of policy)
- [x] Clicking on Save doesn't give any feedback. It should let the user know that it has been saved via a toaster. 
- [ ] Loading screen reflects Fetching Policy - instead, use the loading icon. 
- [x] Remove the condition field as it doesn't specify what the user has to actually add there. 
- [ ] Provide a UI for reflecting the Holiday list as currently, the user won't understand what it actually signifies and how to use it.

**Comment by harshit-30** [comment]
@kamaljohnson if you need any help in understanding what the issue means - please do write here.

**Comment by kamaljohnson** [comment]
@harshit-30, could you give an example for this

> Provide a UI for reflecting the Holiday list as currently, the user won't understand what it actually signifies and how to use it.
