### ISSUE TITLE
Unable to create Frappe Desk Comment with REST API

### ISSUE THREAD

**Issue by jhouxzirrus** [frappe/helpdesk#866]
Using a POST URL like this:
https://mydomain/api/resource/frappe-desk:frappe-desk-comment

I receive this response:
```
{
	"exception": "ImportError: Module import failed for frappe-desk:frappe-desk-comment, the DocType you're trying to open might be deleted.<br> Error: No module named 'frappe.core.doctype.frappe_desk:frappe_desk_comment'",
	"exc": "[\"Traceback (most recent call last):\\n  File...
}
```

This does not work either:
https://mydomain/api/resource/frappe-desk-comment

How does one create a frappe desk comment via REST API?

**Comment by RitvikSardana** [comment]
Part of old helpdesk, hence closing
