### ISSUE TITLE
Missing Create and Assign Ticket Type option 

### ISSUE THREAD

**Issue by shadrak98** [frappe/helpdesk#884]
In the new UI update, while searching for a new ticket type the create a new ticket type option doesn't show up now.

![telegram-cloud-photo-size-5-6129786164350137478-x](https://user-images.githubusercontent.com/30501401/208629146-234b3f6d-3f43-42d1-ae6c-616d8bef5dc4.jpg)

**Comment by harshit-30** [comment]
@fadilsid we can have a similar flow like Github: 
<img width="322" alt="image" src="https://user-images.githubusercontent.com/46772424/214047560-2b832006-16e8-42c5-9475-264c85d99b8d.png">

Let me know your thoughts on TG, we can finalise their.
