### ISSUE TITLE
SLA Status Display in ticket on  Agent Portal

### ISSUE THREAD

**Issue by prasadsamant** [frappe/helpdesk#889]
SLA Status update does not refresh until ticket status is updated.
refer video

**Comment by prasadsamant** [comment]
https://user-images.githubusercontent.com/121442607/209629800-f0af4c3f-14f4-45b0-9fad-8d43f9629397.mov

**Comment by RitvikSardana** [comment]
fixed via https://github.com/frappe/helpdesk/pull/1855
