### ISSUE TITLE
how to change url from frappedesk to custom company name

### ISSUE THREAD

**Issue by rioshaz** [frappe/helpdesk#895]
how to change url from frappedesk to custom company name  ofcourse not just a redirect....

**Comment by kamaljohnson** [comment]
@rioshaz you mean the `/frappedesk/tickets` or `/frappedesk/support` URLs ryt?

you will have to edit the code base to achieve this, for now, there is no option to change the base URL other ways.
also, there are some places where this URL is hard coded, so you would have to change it at all those places too.

but if you do this, it would be difficult to update to newer version of frappedesk.

**Comment by JoSoG89** [comment]
@rioshaz someting like /supportdesk/tickets, change the base /frappedesk/
