### ISSUE TITLE
Make ticket title editable

### ISSUE THREAD

**Issue by shadrak98** [frappe/helpdesk#915]
Once the ticket is created, there is no way for a customer or user to edit the title this feature should atleast be there for user if not agent.

**Comment by harshit-30** [comment]
@fadilsid we need to have a feature where we can edit the subject of the ticket.

**Comment by JoSoG89** [comment]
Can be an option, if in the first reply the system reply with the number of ticket in the subject, example:

Customer mail:
Subject: throuble

ticket reply:
Subject throuble [ticket #168541]

as example, because if a customer call to support will have fast access to know the ticket number

**Comment by fadilsid** [comment]
> @fadilsid we can add a feature where we can edit the subject of the ticket.

@harshit-30  added a feature where  user can edit the subject from customer portal. should we add a feature for agent to edit subject as well?

https://user-images.githubusercontent.com/73826691/213999955-e9617ffd-1887-45f3-94bb-1760cfa4969c.mp4

**Comment by harshit-30** [comment]
@fadilsid it should be only editable by the agent and not by the customer. Customers shouldn't be able to change it.
