### ISSUE TITLE
Submit Ticket Functionality not working

### ISSUE THREAD

**Issue by nestorbird** [frappe/helpdesk#922]
Submit ticket functionality stopped working after the marketplace upgrade.

![Screenshot 2023-01-06 at 5 16 21 PM](https://user-images.githubusercontent.com/121154920/211006458-f22df28e-3c64-4fdb-a548-8852245ee67a.png)

**Comment by nestorbird** [comment]
The whole team is blocked and not able to create anymore tickets.

**Comment by Botanium** [comment]
it is because of the customer as I understand. 

```
Failed to load resource: the server responded with a status of 500 ()
index.df25e30d.js:240 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1590, in call
    return fn(*args, **newargs)
  File "apps/frappedesk/frappedesk/api/ticket.py", line 246, in create_new
    ticket_doc.customer = values["customer"]
KeyError: 'customer'

Ticketing.cabf952b.js:1 create ticket error : Error: frappedesk.api.ticket.create_new
```

**Comment by Botanium** [comment]
if I create a ticket from the Admin portal, I have a cell to select the customer, in that case, the ticket can be submitted without issue. but the actual users who are raising tickets can't create a ticket and I get this error in the console log.

**Comment by kamaljohnson** [comment]
This issue had been fixed in #920 could you please try to update the app to this commit and check?

**Comment by Botanium** [comment]
I tried to update several times, but I don't get the update button on FC.

**Comment by kamaljohnson** [comment]
I had asked the FC team to update the common bench for Frappe Desk, If you go to your site page you will see the update option available.
