### ISSUE TITLE
use capsule design to reflect `Status` in Ticket List 

### ISSUE THREAD

**Issue by harshit-30** [frappe/helpdesk#928]
The colour of each state can be found in the figma file: 

![Screenshot 2022-12-30 at 04 17 58](https://user-images.githubusercontent.com/46772424/210018346-6193dd82-1e4b-4f76-b786-310b264eb6c0.png)

*Closed and Resolved share the same colour

**Comment by harshit-30** [comment]
@kamaljohnson please follow the design, test it and then mark the ticket as closed.

**Comment by fadilsid** [comment]
resolved in d3ca5e2
