### ISSUE TITLE
Customer View - UI fixes

### ISSUE THREAD

**Issue by harshit-30** [frappe/helpdesk#931]
- [x] kill the horizontal scrolling bar introduced here
![Screenshot 2023-01-11 at 19 27 27](https://user-images.githubusercontent.com/46772424/211824715-eed8cf31-35e7-4a4c-b3ab-d94c17e11f61.png)

- [x] the ticket list is not as per the design 
for example, the font size used is 12px instead of 13 and the font used is Sans-sarif instead of Inter and other alignment, padding and size issues.

**Comment by harshit-30** [comment]
@kamaljohnson please don't mark tickets as closed unless you have completed all the tasks mentioned in the issue. 

cc @netchampfaris @nabinhait

**Comment by fadilsid** [comment]
This has been resolved by @kamaljohnson 
![Image](https://user-images.githubusercontent.com/73826691/213546989-cc324568-32d7-4971-9fb8-016c97465ee4.png)
