### ISSUE TITLE
fetch customer based on contact

### ISSUE THREAD

**Issue by harshit-30** [frappe/helpdesk#933]
while creating a new ticket, if the contact selected in the 'Raised by' belongs to a customer - it should automatically fetch that. 

https://user-images.githubusercontent.com/46772424/211827779-6b4cb353-dead-4f28-912c-aae5cc4a3e3c.mp4

**Comment by fadilsid** [comment]
resolved in #947 [6dfc218](https://github.com/frappe/helpdesk/pull/947/commits/6dfc218255d9a5a7b4c0f4572593bbcd1c82a335)
