### ISSUE TITLE
how can i customize new ticket form of customer portal?

### ISSUE THREAD

**Issue by NayanGajjar** [frappe/helpdesk#943]
how can i customize new ticket from of customer portal? @kamaljohnson

![image](https://user-images.githubusercontent.com/122445476/211989134-a7f18ea0-a761-419c-94e1-3dd57d212f1a.png)

**Comment by harshit-30** [comment]
same as #927

**Comment by NayanGajjar** [comment]
can't we do that???

**Comment by harshit-30** [comment]
not currently.

**Comment by harshit-30** [comment]
@NayanGajjar currently it is on the roadmap, but not on the priority list. If you wish to sponsor this feature, please email on harshit@frappe.io to discuss further.
