### ISSUE TITLE
add the ability to Cc and Bcc

### ISSUE THREAD

**Issue by harshit-30** [frappe/helpdesk#945]
The design to have a Cc and Bcc functionality is below. [Figma link](https://www.figma.com/file/RZ8zihVNkek1M5t87ZAdcC/FD---Tridz?node-id=297%3A1150&t=Ao85CJePQNAOFUz1-4). 

Please refer to the design, we have added a few small changes in the Reply component. 

![cc option-1](https://user-images.githubusercontent.com/46772424/212085013-5bc1785f-8c71-49cf-9711-3fcad9e3e2b5.png)
![cc option-2](https://user-images.githubusercontent.com/46772424/212085020-a7ba0ca3-b367-4b0e-957a-5c0befb2c04c.png)
![cc option](https://user-images.githubusercontent.com/46772424/212085026-f8941e6d-d241-45f0-b617-e8175d0a0d9f.png)

**Comment by fadilsid** [comment]
resolved in #954
