### ISSUE TITLE
fix: customer info broken design 

### ISSUE THREAD

**Issue by harshit-30** [frappe/helpdesk#957]
The design is breaking, please design it as per the Figma file _(will share with @ssiyad internally)_:
Three components in the following screenshot: 

- [ ] Customer Info
- [ ] Open Tickets
- [ ] Ticket History
All three are broken currently. 

<img width="360" alt="image" src="https://user-images.githubusercontent.com/46772424/213678125-956d52f6-17e0-4233-b1ce-1e82aeda388f.png"> <img width="333" alt="image" src="https://user-images.githubusercontent.com/46772424/213679098-25d8570e-71a4-4458-bcb7-46d6260d7685.png">

**Comment by ssiyad** [comment]
closed in https://github.com/frappe/helpdesk/pull/1042
