### ISSUE TITLE
ui: ticket list subject padding

### ISSUE THREAD

**Issue by harshit-30** [frappe/helpdesk#958]
- [ ] Decrease the padding of the subject column 
- [ ] Increase the font size of '#' _(ticket number)_ column from 11 to 13 

Please refer to the Figma design file for any help. 

<img width="413" alt="image" src="https://user-images.githubusercontent.com/46772424/213684360-c663b7ec-4910-4b4d-8efa-00c983b4dbf8.png">

**Comment by harshit-30** [comment]
@ssiyad There were two tasks in that issue - are both of them addressed in this PR?

**Comment by ssiyad** [comment]
@harshit-30 nope, just 2nd one. 1st will be another PR
