### ISSUE TITLE
add `All Open Tickets` in preset filters

### ISSUE THREAD

**Issue by harshit-30** [frappe/helpdesk#963]
Add a filter in the presets `All Open Tickets` above `All Tickets` and make it as default.
Currently, `All tickets` is the default. 

<img width="209" alt="image" src="https://user-images.githubusercontent.com/46772424/214559589-6e681b32-85f1-4f89-b816-dccacc315829.png">

**Comment by virenderpccvdi** [comment]
Hi,

There no ticket, user, account, agent is showing in dashboard in frappe 14, 

Few week before all working fine

**Comment by ssiyad** [comment]
@virenderpccvdi can you verify if they're available in backend? also, which version/commit are you running?

**Comment by virenderpccvdi** [comment]
Hi.

Yes in backend all is showing well only issue with dashboard FF-0.6 .

github URL : bench get-app https://github.com/frappe/desk

**Comment by ssiyad** [comment]
@virenderpccvdi can you give me a commit please?

**Comment by virenderpccvdi** [comment]
Hi.

Please find the all attached img for more details 


![Image](https://user-images.githubusercontent.com/45853723/221526307-18c544f4-d291-4978-92d2-2c72bcf277bf.PNG)



![Image](https://user-images.githubusercontent.com/45853723/221527817-bff6d9e9-6d3b-4506-9324-6ac41a3d9521.PNG)
![Image](https://user-images.githubusercontent.com/45853723/221527816-38e9adc4-5e26-42e4-a912-b33474c70905.PNG)

**Comment by virenderpccvdi** [comment]
Hi Team,

Can you please guide us on the same.

**Comment by harshit-30** [comment]
@virenderpccvdi please communicate with us on Telegram for direct communication - https://t.me/frappedesk. 

Please create new issues instead of commenting on an existing one.
