### ISSUE TITLE
Tickets not displaying description other than Subject line

### ISSUE THREAD

**Issue by ashishsaretia** [frappe/helpdesk#968]
Most of the tickets are blank and to check the description we have to switch to /app/ticket/0006167 instead of /frappe-desk

![Screenshot 2023-01-31 at 2 24 28 PM](https://user-images.githubusercontent.com/10839039/215713663-428360d0-570b-40cb-8dad-b1894be9a73a.png)

![Screenshot 2023-01-31 at 2 22 57 PM](https://user-images.githubusercontent.com/10839039/215713510-d374f59f-e67a-47d7-8a14-8b2a49ae18b0.png)

**Comment by harshit-30** [comment]
how did you create this issue? via email, customer portal or manually from ticket doctype?

**Comment by ashishsaretia** [comment]
Ticket was created by user via customer portal

**Comment by harshit-30** [comment]
can you replicate this?

**Comment by ashishsaretia** [comment]
Certainly, but this happens with most of the tickets, not every time though. I can pull the tickets where this issue is residing.

![image](https://user-images.githubusercontent.com/10839039/215716013-2b9f1e2c-70d2-419d-85bc-fe6acd002f5d.png)

**Comment by ashishsaretia** [comment]
![Screenshot 2023-03-10 at 10 52 12 AM](https://user-images.githubusercontent.com/10839039/224231200-be1f33a1-b74d-4bf4-8689-f884ec1c2b68.png)
https://support.nestorbird.com/frappedesk/tickets/0010177

**Comment by RitvikSardana** [comment]
Part of old helpdesk, hence closing
