### ISSUE TITLE
make ticket DocType fields customizable for to be reflected on agent portal

### ISSUE THREAD

**Issue by harshit-30** [frappe/helpdesk#975]
**Problem**
Currently, the fields that can be only made visible to the customer are the custom fields. 
there are different fields like a priority, SLA fields, and ticket type that the companies require to reflect on the customer end. 

**Solution**
Remove this restriction and let the admins select whatever field they wish to reflect on the customer's end.

**Comment by RitvikSardana** [comment]
It is solved and can be done via HD Ticket Template DocType
